"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Heart,ShoppingCart,Search,Star,Trash2,Minus,Plus,ShieldCheck,Truck,CheckCircle2,AlertTriangle,CreditCard,PackageCheck,RotateCcw,LockKeyhole,BadgeCheck,MapPin} from "lucide-react";
import {Product,products,money,bySlug} from "../lib/catalog";

type CartLine={id:string;qty:number;variant?:Record<string,string>};
type BuilderState={processor?:string;motherboard?:string;memory?:string;gpu?:string;psu?:string;case?:string;storage?:string;cooling?:string;monitor?:string};

const CART_KEY="nexrig_cart_v1", WISH_KEY="nexrig_wishlist_v1", BUILD_KEY="nexrig_builder_v1";
const PAYMENT_BADGES=["VISA","Mastercard","JCB","QRIS","BCA","Mandiri","BNI","BRI","GoPay","OVO","DANA","ShopeePay"];
function safeRead<T>(k:string,fallback:T):T{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(k)||"") as T}catch{return fallback}}
function productMatches(p:Product,q:string){const s=(p.name+" "+p.category+" "+p.brand+" "+Object.values(p.specs).join(" ")).toLowerCase();return s.includes(q.toLowerCase())}

function useStore(){
 const [cart,setCart]=useState<CartLine[]>([]); const [wish,setWish]=useState<string[]>([]); const [builder,setBuilder]=useState<BuilderState>({});
 useEffect(()=>{setCart(safeRead(CART_KEY,[]));setWish(safeRead(WISH_KEY,[]));setBuilder(safeRead(BUILD_KEY,{}))},[]);
 useEffect(()=>{if(typeof window!=="undefined")localStorage.setItem(CART_KEY,JSON.stringify(cart))},[cart]);
 useEffect(()=>{if(typeof window!=="undefined")localStorage.setItem(WISH_KEY,JSON.stringify(wish))},[wish]);
 useEffect(()=>{if(typeof window!=="undefined")localStorage.setItem(BUILD_KEY,JSON.stringify(builder))},[builder]);
 const add=(id:string,variant?:Record<string,string>)=>setCart(c=>{const i=c.findIndex(x=>x.id===id&&JSON.stringify(x.variant||{})===JSON.stringify(variant||{}));if(i<0)return[...c,{id,qty:1,variant}];return c.map((x,n)=>n===i?{...x,qty:x.qty+1}:x)});
 const qty=(id:string,n:number)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(1,n)}:x));
 const remove=(id:string)=>setCart(c=>c.filter(x=>x.id!==id));
 const toggleWish=(id:string)=>setWish(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id]);
 return{cart,wish,builder,setBuilder,add,qty,remove,toggleWish,setCart};
}

function Header({cartCount,wishCount}:{cartCount:number;wishCount:number}){return <header className="topbar"><Link href="/" className="brand">NEX<span>RIG</span></Link><div className="actions"><Link href="/search" aria-label="Search"><Search size={21}/></Link><Link href="/wishlist" aria-label="Wishlist" className="iconCounter"><Heart size={21}/>{wishCount>0&&<b>{wishCount}</b>}</Link><Link href="/cart" aria-label="Cart" className="iconCounter"><ShoppingCart size={21}/>{cartCount>0&&<b>{cartCount}</b>}</Link></div></header>}

function PaymentBadges(){return <div className="paymentBadgeGrid">{PAYMENT_BADGES.map(x=><span key={x}>{x}</span>)}</div>}

function ProductCard({p,wished,onWish,onAdd}:{p:Product;wished:boolean;onWish:()=>void;onAdd:()=>void}){return <article className="commerceCard"><div className="productImage"><Link href={`/product/${p.slug}`}><img src={p.image} alt={p.name}/></Link>{p.badge&&<span className="badge">{p.badge}</span>}<button className={`wishBtn ${wished?"active":""}`} onClick={onWish} aria-label="Wishlist"><Heart size={18} fill={wished?"currentColor":"none"}/></button></div><div className="commerceBody"><span className="cat">{p.category}</span><Link href={`/product/${p.slug}`}><h3>{p.name}</h3></Link><div className="rating"><Star size={14} fill="currentColor"/> {p.rating} <small>({p.reviews})</small></div><div className="priceRow"><strong>{money(p.price)}</strong>{p.oldPrice&&<del>{money(p.oldPrice)}</del>}</div><div className="stockRow">{p.stock>0?`${p.stock} ready stock`:"Out of stock"}</div><button className="addBtn" disabled={!p.stock} onClick={onAdd}>Add to cart</button></div></article>}

function FilterableCatalog({initialCategory="all",store}:{initialCategory?:string;store:ReturnType<typeof useStore>}){
 const [q,setQ]=useState(""); const [sort,setSort]=useState("popular"); const [onlyStock,setOnlyStock]=useState(true); const [maxPrice,setMaxPrice]=useState(20000000); const [category,setCategory]=useState(initialCategory);
 const list=useMemo(()=>products.filter(p=>(category==="all"||p.categorySlug===category)&&(!q||productMatches(p,q))&&(!onlyStock||p.stock>0)&&p.price<=maxPrice).sort((a,b)=>sort==="price-asc"?a.price-b.price:sort==="price-desc"?b.price-a.price:sort==="rating"?b.rating-a.rating:b.reviews-a.reviews),[q,sort,onlyStock,maxPrice,category]);
 return <><div className="commerceToolbar"><div className="searchField"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search this category..."/></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">Most Popular</option><option value="rating">Best Rating</option><option value="price-asc">Price: Low to High</option><option value="price-desc">Price: High to Low</option></select></div><div className="catalogLayout"><aside className="filterPanel"><h3>Filters</h3><label><span>Category</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All Components</option>{[...new Set(products.map(p=>p.categorySlug))].map(x=><option key={x} value={x}>{products.find(p=>p.categorySlug===x)?.category}</option>)}</select></label><label className="checkLine"><input type="checkbox" checked={onlyStock} onChange={e=>setOnlyStock(e.target.checked)}/> Ready stock only</label><label><span>Maximum price</span><input type="range" min="250000" max="20000000" step="250000" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/><b>{money(maxPrice)}</b></label><p>{list.length} products</p></aside><div><div className="commerceGrid">{list.map(p=><ProductCard key={p.id} p={p} wished={store.wish.includes(p.id)} onWish={()=>store.toggleWish(p.id)} onAdd={()=>store.add(p.id)}/>)}</div>{!list.length&&<div className="emptyState">No products match these filters.</div>}</div></div></>
}

function SearchPage({store}:{store:ReturnType<typeof useStore>}){const[q,setQ]=useState("");const results=useMemo(()=>q.trim()?products.filter(p=>productMatches(p,q)).slice(0,12):products.slice(0,8),[q]);return <section className="contentSection commerceSection"><div className="searchHero"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search GPU, DDR5, 850W, 180Hz..."/></div>{q&&<div className="autosuggest"><span>Suggestions:</span>{products.filter(p=>productMatches(p,q)).slice(0,6).map(p=><Link key={p.id} href={`/product/${p.slug}`}>{p.name}</Link>)}</div>}<div className="commerceGrid">{results.map(p=><ProductCard key={p.id} p={p} wished={store.wish.includes(p.id)} onWish={()=>store.toggleWish(p.id)} onAdd={()=>store.add(p.id)}/>)}</div></section>}

function ProductPage({slug,store}:{slug:string;store:ReturnType<typeof useStore>}){
 const p=bySlug(slug)||products[0];
 const [variant,setVariant]=useState<Record<string,string>>(()=>Object.fromEntries((p.variants||[]).map(v=>[v.name,v.values[0]])));
 const related=products.filter(x=>x.id!==p.id&&(x.categorySlug===p.categorySlug||x.categorySlug!==p.categorySlug)).slice(0,8);
 const paired=products.filter(x=>x.id!==p.id&&x.categorySlug!==p.categorySlug).slice(0,4);
 const discount=p.oldPrice?Math.round((1-p.price/p.oldPrice)*100):0;
 const buyNow=()=>{store.add(p.id,variant);if(typeof window!=="undefined")window.location.href="/checkout"};
 return <section className="productCommerce productV2">
  <div className="productBreadcrumb"><Link href="/">Home</Link><span>/</span><Link href={`/category/${p.categorySlug}`}>{p.category}</Link><span>/</span><b>{p.name}</b></div>
  <div className="detailGrid productTopGrid">
   <div className="productGallery"><div className="productStage hasImage"><img src={p.image} alt={p.name}/>{p.badge&&<span className="galleryBadge">{p.badge}</span>}</div><div className="thumbRow imageThumbs">{["Front","Detail","Package","Build view"].map(x=><button key={x}><img src={p.image} alt={`${p.name} ${x}`}/><b>{x}</b></button>)}</div></div>
   <div className="buyBox productBuyBox"><div className="rating big"><Star fill="currentColor"/> {p.rating} <span>· {p.reviews} verified reviews</span></div><span className="productBrand">{p.brand} · {p.category}</span><h1>{p.name}</h1><p className="productLead">{p.description}</p><div className="priceCluster"><p className="price">{money(p.price)}</p>{p.oldPrice&&<><del>{money(p.oldPrice)}</del><span className="discountPill">SAVE {discount}%</span></>}</div><p className={p.stock<5?"stock low":"stock"}>● {p.stock>0?`${p.stock} units ready to ship`:"Out of stock"}</p>
   {(p.variants||[]).map(v=><div className="variant" key={v.name}><b>{v.name}</b><div>{v.values.map(x=><button className={variant[v.name]===x?"selected":""} onClick={()=>setVariant(s=>({...s,[v.name]:x}))} key={x}>{x}</button>)}</div></div>)}
   <div className="productCtas"><button className="primaryBuy" disabled={!p.stock} onClick={()=>store.add(p.id,variant)}>Add to Cart</button><button className="quickBuy" disabled={!p.stock} onClick={buyNow}>Buy Now</button><button className={`wishWide ${store.wish.includes(p.id)?"active":""}`} onClick={()=>store.toggleWish(p.id)}><Heart size={17} fill={store.wish.includes(p.id)?"currentColor":"none"}/>{store.wish.includes(p.id)?"Saved to Wishlist":"Add to Wishlist"}</button></div>
   <div className="commerceTrustGrid"><span><ShieldCheck/><b>Official Warranty</b><small>Original product protection</small></span><span><Truck/><b>Fast Delivery</b><small>Tracked nationwide shipping</small></span><span><RotateCcw/><b>Easy Support</b><small>Pre & post purchase help</small></span><span><LockKeyhole/><b>Secure Checkout</b><small>Protected payment flow</small></span></div>
   <div className="productPaymentBlock"><div><CreditCard size={18}/><b>Flexible payment options</b></div><PaymentBadges/><small>Gateway-ready for QRIS, VA, cards and e-wallets. Live charging is not enabled yet.</small></div>
   </div>
  </div>
  <section className="contentSection productStory"><div className="storyIntro"><span className="kicker">WHY THIS PRODUCT</span><h2>Built for the way you actually game.</h2><p>{p.description} NEXRIG pairs every component with clear compatibility guidance, transparent specifications, and a practical upgrade path so you can build confidently instead of guessing.</p></div><div className="sellingPoints"><article><BadgeCheck/><b>Performance-first</b><p>Chosen for stable gaming loads, responsive frame delivery, and balanced system performance.</p></article><article><PackageCheck/><b>Build-ready</b><p>Specifications are structured to make compatibility checks with surrounding components straightforward.</p></article><article><ShieldCheck/><b>Protected purchase</b><p>Official-warranty positioning, support guidance, and clear stock information before checkout.</p></article></div></section>
  <section className="contentSection productInfoGrid"><div><span className="kicker">TECHNICAL DETAIL</span><h2>Specifications</h2><div className="specTable v2">{Object.entries(p.specs).map(([k,v])=><span key={k}>{k}<b>{v}</b></span>)}</div></div><div className="compatPanel"><h3>Compatibility guidance</h3><p>Use PC Builder to validate socket, memory generation, PSU headroom, GPU clearance, and cooling support before checkout.</p><Link href="/builder">Check this in PC Builder →</Link><h3>In the box</h3><ul><li>{p.name}</li><li>Retail packaging</li><li>Warranty documentation</li><li>Installation / quick-start material where applicable</li></ul></div></section>
  <section className="contentSection reviewSection"><div className="reviewScore"><strong>{p.rating}</strong><div><div className="rating"><Star fill="currentColor"/> Excellent</div><span>Based on {p.reviews} reviews</span></div></div><div className="reviewBars">{[[5,78],[4,16],[3,4],[2,1],[1,1]].map(([n,w])=><div key={n}><span>{n}★</span><i><b style={{width:`${w}%`}}/></i><small>{w}%</small></div>)}</div><div className="reviewCards"><article><b>Verified buyer</b><div>★★★★★</div><p>Clean packaging, clear specs, and the compatibility guidance made the purchase much easier.</p></article><article><b>Gaming build customer</b><div>★★★★★</div><p>Performance matched the expected build tier and delivery tracking was straightforward.</p></article></div></section>
  <section className="contentSection faqSection"><span className="kicker">PRODUCT FAQ</span><h2>Questions before you buy</h2>{["Is this product compatible with my current PC?","Does NEXRIG provide warranty support?","Can I use installment or QRIS payment?","Can NEXRIG help me complete the build?"].map((q,i)=><details key={q} open={i===0}><summary>{q}</summary><p>{i===0?"Use the PC Builder compatibility engine or compare the technical specifications above. We surface the key socket, memory, power, form-factor and clearance constraints available in the catalog.":i===1?"The storefront is designed around original products and official/distributor warranty information. Final warranty terms will be attached to each SKU when the backend catalog goes live.":i===2?"The checkout UI already supports QRIS, Virtual Account, cards, bank transfer and e-wallet presentation. Live payment processing will be activated when the payment gateway backend is connected.":"Yes. The PC Builder can assemble a compatible parts list and add the complete build to cart in one action."}</p></details>)}</section>
  <section className="contentSection"><div className="sectionHead"><div><span className="kicker">COMPLETE THE BUILD</span><h2>Frequently bought together</h2></div><Link href="/builder">Open PC Builder</Link></div><div className="commerceGrid">{paired.map(x=><ProductCard key={x.id} p={x} wished={store.wish.includes(x.id)} onWish={()=>store.toggleWish(x.id)} onAdd={()=>store.add(x.id)}/>)}</div><div className="sectionHead productRelatedHead"><div><span className="kicker">KEEP EXPLORING</span><h2>Related components</h2></div></div><div className="commerceGrid">{related.map(x=><ProductCard key={x.id} p={x} wished={store.wish.includes(x.id)} onWish={()=>store.toggleWish(x.id)} onAdd={()=>store.add(x.id)}/>)}</div></section>
 </section>
}

function CartPage({store}:{store:ReturnType<typeof useStore>}){const lines=store.cart.map(l=>({l,p:products.find(p=>p.id===l.id)})).filter(x=>x.p) as {l:CartLine,p:Product}[];const subtotal=lines.reduce((s,x)=>s+x.p.price*x.l.qty,0);return <section className="contentSection checkoutLayout"><div><h2>Shopping Cart</h2>{lines.length?lines.map(({l,p})=><div className="cartLine" key={p.id}><img src={p.image} alt={p.name}/><div><Link href={`/product/${p.slug}`}><b>{p.name}</b></Link><span>{money(p.price)}</span><div className="qtyCtrl"><button onClick={()=>store.qty(p.id,l.qty-1)}><Minus size={14}/></button><b>{l.qty}</b><button onClick={()=>store.qty(p.id,l.qty+1)}><Plus size={14}/></button></div></div><strong>{money(p.price*l.qty)}</strong><button onClick={()=>store.remove(p.id)}><Trash2 size={18}/></button></div>):<div className="emptyState">Your cart is empty. <Link href="/category/all">Shop components</Link></div>}</div><aside className="orderSummary"><h3>Order Summary</h3><span>Subtotal<b>{money(subtotal)}</b></span><span>Shipping<b>{subtotal>=3000000?"FREE":"Rp 50.000"}</b></span><span>Total<b>{money(subtotal+(subtotal&&subtotal<3000000?50000:0))}</b></span><Link href={lines.length?"/checkout":"/category/all"}>{lines.length?"Proceed to Checkout":"Start Shopping"}</Link></aside></section>}

function WishlistPage({store}:{store:ReturnType<typeof useStore>}){const list=products.filter(p=>store.wish.includes(p.id));return <section className="contentSection commerceSection"><h2>Your Wishlist</h2>{list.length?<div className="commerceGrid">{list.map(p=><ProductCard key={p.id} p={p} wished onWish={()=>store.toggleWish(p.id)} onAdd={()=>store.add(p.id)}/>)}</div>:<div className="emptyState">No saved products yet. Tap the heart on any product.</div>}</section>}

function CheckoutPage({store}:{store:ReturnType<typeof useStore>}){
 const[placed,setPlaced]=useState(false); const[method,setMethod]=useState("qris"); const[shipping,setShipping]=useState("regular"); const[voucher,setVoucher]=useState(""); const[applied,setApplied]=useState(false);
 const subtotal=store.cart.reduce((s,l)=>{const p=products.find(p=>p.id===l.id);return s+(p?p.price*l.qty:0)},0); const shippingCost=shipping==="instant"?75000:shipping==="same-day"?45000:subtotal>=3000000?0:25000; const discount=applied?Math.min(50000,subtotal):0; const total=Math.max(0,subtotal+shippingCost-discount);
 if(placed)return <section className="contentSection successOrder orderSuccessV2"><CheckCircle2 size={64}/><span className="kicker">ORDER RECEIVED</span><h2>Thank you. Your order is ready for payment.</h2><p>Order ID <b>NX-{Date.now().toString().slice(-8)}</b></p><div className="successSteps"><span><CheckCircle2/>Order created</span><span><CreditCard/>Payment instruction prepared</span><span><Truck/>Shipping will activate after payment</span></div><p className="demoNote">This is still a UI flow. No real charge has been created yet.</p><Link href="/">Continue Shopping</Link></section>;
 return <section className="checkoutV2">
  <div className="checkoutStepper"><span className="done"><b>1</b>Cart</span><i/><span className="active"><b>2</b>Shipping</span><i/><span><b>3</b>Payment</span><i/><span><b>4</b>Review</span></div>
  <section className="contentSection checkoutLayout checkoutGridV2"><form className="checkoutForm" onSubmit={e=>{e.preventDefault();if(store.cart.length){setPlaced(true);store.setCart([])}}}><div className="checkoutBlock"><div className="checkoutBlockTitle"><MapPin/><div><h2>Shipping address</h2><p>Where should we send your NEXRIG gear?</p></div></div><div className="formGrid"><label>Full name<input required placeholder="Your full name"/></label><label>Phone<input required placeholder="08xxxxxxxxxx"/></label><label className="wide">Address<textarea required placeholder="Street, building, district, notes"/></label><label>City<input required placeholder="Jakarta"/></label><label>Postal code<input required placeholder="14460"/></label></div></div>
   <div className="checkoutBlock"><div className="checkoutBlockTitle"><Truck/><div><h3>Delivery option</h3><p>Select speed before payment.</p></div></div>{[["regular","Regular","2–4 business days",subtotal>=3000000?0:25000],["same-day","Same Day","Available in selected areas",45000],["instant","Instant","Courier delivery",75000]].map(([id,title,desc,cost]:any)=><label className={`shippingCard ${shipping===id?"selected":""}`} key={id}><input type="radio" name="shipping" checked={shipping===id} onChange={()=>setShipping(id)}/><div><b>{title}</b><span>{desc}</span></div><strong>{cost===0?"FREE":money(cost)}</strong></label>)}</div>
   <div className="checkoutBlock"><div className="checkoutBlockTitle"><CreditCard/><div><h3>Payment method</h3><p>Choose a gateway-ready payment route.</p></div></div><div className="paymentMethodGrid">{[["qris","QRIS","Scan & pay","QRIS"],["va","Virtual Account","BCA · Mandiri · BNI · BRI","VA"],["card","Credit / Debit Card","Visa · Mastercard · JCB","CARD"],["wallet","E-Wallet","GoPay · OVO · DANA · ShopeePay","WALLET"],["bank","Bank Transfer","Manual bank transfer","BANK"]].map(([id,title,desc,badge])=><label className={`paymentCard ${method===id?"selected":""}`} key={id}><input type="radio" name="pay" checked={method===id} onChange={()=>setMethod(id)}/><span className="payMark">{badge}</span><div><b>{title}</b><small>{desc}</small></div></label>)}</div><div className="gatewayNotice"><LockKeyhole/><div><b>Payment Gateway</b><span>UI prepared for Midtrans / Xendit / DOKU-style integration. Real charging remains disabled until backend credentials are connected.</span></div></div><PaymentBadges/></div>
   <label className="termsLine"><input type="checkbox" required/> I confirm my shipping information and agree to the store terms.</label><button className="placeOrder stickyPay" disabled={!store.cart.length}>Pay {money(total)}</button></form>
   <aside className="orderSummary orderSummaryV2"><h3>Your Order</h3><div className="checkoutItems">{store.cart.map(l=>{const p=products.find(p=>p.id===l.id);return p?<div key={p.id}><img src={p.image} alt={p.name}/><span><b>{p.name}</b><small>Qty {l.qty}</small></span><strong>{money(p.price*l.qty)}</strong></div>:null})}</div><div className="voucherBox"><input value={voucher} onChange={e=>setVoucher(e.target.value)} placeholder="Voucher code"/><button type="button" onClick={()=>setApplied(voucher.trim().toUpperCase()==="NEXRIG50")}>{applied?"Applied":"Apply"}</button></div>{voucher&&!applied&&<small className="voucherHint">Try NEXRIG50 for this UI demo.</small>}<span>Subtotal<b>{money(subtotal)}</b></span><span>Shipping<b>{shippingCost?money(shippingCost):"FREE"}</b></span>{discount>0&&<span className="discountLine">Voucher<b>-{money(discount)}</b></span>}<span className="grandTotal">Total<b>{money(total)}</b></span><div className="summaryTrust"><ShieldCheck/><p><b>Protected checkout</b><small>Order summary is reviewed before any future gateway charge.</small></p></div></aside>
  </section>
 </section>
}

function isCompatible(builder:BuilderState){const cpu=products.find(p=>p.id===builder.processor),mb=products.find(p=>p.id===builder.motherboard),ram=products.find(p=>p.id===builder.memory),gpu=products.find(p=>p.id===builder.gpu),psu=products.find(p=>p.id===builder.psu),pcase=products.find(p=>p.id===builder.case),cool=products.find(p=>p.id===builder.cooling);const issues:string[]=[];if(cpu&&mb&&cpu.specs.Socket!==mb.specs.Socket)issues.push("CPU socket does not match motherboard.");if(ram&&mb&&ram.specs.Type!==mb.specs.Memory)issues.push("Memory generation does not match motherboard.");if(gpu&&psu&&Number(psu.specs.Wattage.replace(/\D/g,""))<850)issues.push("Selected GPU requires at least 850W PSU.");if(gpu&&pcase&&Number(pcase.specs.GPUClearance.replace(/\D/g,""))<Number(gpu.specs.Length.replace(/\D/g,"")))issues.push("GPU is too long for the selected case.");if(cool&&cpu&&!cool.specs.Sockets.includes(cpu.specs.Socket))issues.push("CPU cooler does not support selected CPU socket.");return issues}
function BuilderPage({store}:{store:ReturnType<typeof useStore>}){const slots=[['processor','Processor'],['motherboard','Motherboard'],['memory','Memory'],['gpu','Graphics Card'],['storage','Storage'],['psu','Power Supply'],['case','Gaming Case'],['cooling','Cooling'],['monitor','Monitor']] as const;const issues=isCompatible(store.builder);const total=Object.values(store.builder).reduce((s,id)=>{const p=products.find(p=>p.id===id);return s+(p?.price||0)},0);return <section className="contentSection builderEngine"><div className="builderHead"><div><span className="kicker">PC COMPATIBILITY ENGINE</span><h2>Build your NEXRIG</h2></div><strong>{money(total)}</strong></div>{issues.length?<div className="compat bad"><AlertTriangle/>{issues.map(x=><span key={x}>{x}</span>)}</div>:<div className="compat good"><CheckCircle2/>Current selections are compatible.</div>}<div className="builderSlotGrid">{slots.map(([key,label])=>{const candidates=products.filter(p=>key==='gpu'?p.categorySlug==='graphics-card':key==='case'?p.categorySlug==='gaming-case':p.categorySlug===key);const selected=products.find(p=>p.id===store.builder[key]);return <div className="builderSlot" key={key}><b>{label}</b>{selected&&<div className="builderSelected"><img src={selected.image} alt={selected.name}/><span>{selected.name}</span></div>}<select value={store.builder[key]||""} onChange={e=>store.setBuilder(b=>({...b,[key]:e.target.value||undefined}))}><option value="">Select {label}</option>{candidates.map(p=><option value={p.id} key={p.id}>{p.name} · {money(p.price)}</option>)}</select></div>})}</div><button className="addBuild" disabled={issues.length>0||Object.keys(store.builder).length<4} onClick={()=>Object.values(store.builder).forEach(id=>id&&store.add(id))}>Add compatible build to cart</button></section>}

export default function CommerceEngine({mode,slug}:{mode:string;slug?:string}){const store=useStore();const cartCount=store.cart.reduce((s,x)=>s+x.qty,0);return <main><Header cartCount={cartCount} wishCount={store.wish.length}/>{mode==="category"&&<section className="contentSection commerceSection"><div className="pageTitle"><span className="kicker">SHOP COMPONENTS</span><h1>{slug==="all"?"All Gaming Components":products.find(p=>p.categorySlug===slug)?.category||"Gaming Components"}</h1></div><FilterableCatalog initialCategory={slug||"all"} store={store}/></section>}{mode==="search"&&<SearchPage store={store}/>} {mode==="product"&&<ProductPage slug={slug||products[0].slug} store={store}/>} {mode==="cart"&&<CartPage store={store}/>} {mode==="wishlist"&&<WishlistPage store={store}/>} {mode==="checkout"&&<CheckoutPage store={store}/>} {mode==="builder"&&<BuilderPage store={store}/>}<nav className="bottomNav"><Link href="/">Home</Link><Link href="/category/all">Categories</Link><Link href="/search">Search</Link><Link href="/wishlist">Wishlist</Link><Link href="/cart">Cart</Link></nav></main>}
