"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Heart,ShoppingCart,Search,Star,Trash2,Minus,Plus,ShieldCheck,Truck,CheckCircle2,AlertTriangle} from "lucide-react";
import {Product,products,money,bySlug} from "../lib/catalog";

type CartLine={id:string;qty:number;variant?:Record<string,string>};
type BuilderState={processor?:string;motherboard?:string;memory?:string;gpu?:string;psu?:string;case?:string;storage?:string;cooling?:string;monitor?:string};

const CART_KEY="nexrig_cart_v1", WISH_KEY="nexrig_wishlist_v1", BUILD_KEY="nexrig_builder_v1";
function safeRead<T>(k:string,fallback:T):T{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(k)||"") as T}catch{return fallback}}
function productMatches(p:Product,q:string){const s=(p.name+" "+p.category+" "+p.brand+" "+Object.values(p.specs).join(" ")).toLowerCase();return s.includes(q.toLowerCase())}

function useStore(){
 const [cart,setCart]=useState<CartLine[]>([]); const [wish,setWish]=useState<string[]>([]); const [builder,setBuilder]=useState<BuilderState>({});
 useEffect(()=>{setCart(safeRead(CART_KEY,[]));setWish(safeRead(WISH_KEY,[]));setBuilder(safeRead(BUILD_KEY,{}))},[]);
 useEffect(()=>{if(typeof window!=="undefined")localStorage.setItem(CART_KEY,JSON.stringify(cart))},[cart]);
 useEffect(()=>{if(typeof window!=="undefined")localStorage.setItem(WISH_KEY,JSON.stringify(wish))},[wish]);
 useEffect(()=>{if(typeof window!=="undefined")localStorage.setItem(BUILD_KEY,JSON.stringify(builder))},[builder]);
 const add=(id:string,variant?:Record<string,string>)=>setCart(c=>{const i=c.findIndex(x=>x.id===id&&JSON.stringify(x.variant||{})===JSON.stringify(variant||{}));if(i<0)return[...c,{id,qty:1,variant}];return c.map((x,n)=>n===i?{...x,qty:x.qty+1}:x)});
 const qty=(id:string,n:number)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(1,n)}:x));
 const remove=(id:string)=>setCart(c=>c.filter(x=>x.id!==id));
 const toggleWish=(id:string)=>setWish(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id]);
 return{cart,wish,builder,setBuilder,add,qty,remove,toggleWish,setCart};
}

function Header({cartCount,wishCount}:{cartCount:number;wishCount:number}){return <header className="topbar"><Link href="/" className="brand">NEX<span>RIG</span></Link><div className="actions"><Link href="/search" aria-label="Search"><Search size={21}/></Link><Link href="/wishlist" aria-label="Wishlist" className="iconCounter"><Heart size={21}/>{wishCount>0&&<b>{wishCount}</b>}</Link><Link href="/cart" aria-label="Cart" className="iconCounter"><ShoppingCart size={21}/>{cartCount>0&&<b>{cartCount}</b>}</Link></div></header>}

function ProductCard({p,wished,onWish,onAdd}:{p:Product;wished:boolean;onWish:()=>void;onAdd:()=>void}){return <article className="commerceCard"><div className="productImage"><Link href={`/product/${p.slug}`}><img src={p.image} alt={p.name}/></Link>{p.badge&&<span className="badge">{p.badge}</span>}<button className={`wishBtn ${wished?"active":""}`} onClick={onWish} aria-label="Wishlist"><Heart size={18} fill={wished?"currentColor":"none"}/></button></div><div className="commerceBody"><span className="cat">{p.category}</span><Link href={`/product/${p.slug}`}><h3>{p.name}</h3></Link><div className="rating"><Star size={14} fill="currentColor"/> {p.rating} <small>({p.reviews})</small></div><div className="priceRow"><strong>{money(p.price)}</strong>{p.oldPrice&&<del>{money(p.oldPrice)}</del>}</div><div className="stockRow">{p.stock>0?`${p.stock} ready stock`:"Out of stock"}</div><button className="addBtn" disabled={!p.stock} onClick={onAdd}>Add to cart</button></div></article>}

function FilterableCatalog({initialCategory="all",store}:{initialCategory?:string;store:ReturnType<typeof useStore>}){
 const [q,setQ]=useState(""); const [sort,setSort]=useState("popular"); const [onlyStock,setOnlyStock]=useState(true); const [maxPrice,setMaxPrice]=useState(20000000); const [category,setCategory]=useState(initialCategory);
 const list=useMemo(()=>products.filter(p=>(category==="all"||p.categorySlug===category)&&(!q||productMatches(p,q))&&(!onlyStock||p.stock>0)&&p.price<=maxPrice).sort((a,b)=>sort==="price-asc"?a.price-b.price:sort==="price-desc"?b.price-a.price:sort==="rating"?b.rating-a.rating:b.reviews-a.reviews),[q,sort,onlyStock,maxPrice,category]);
 return <><div className="commerceToolbar"><div className="searchField"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search this category..."/></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">Most Popular</option><option value="rating">Best Rating</option><option value="price-asc">Price: Low to High</option><option value="price-desc">Price: High to Low</option></select></div><div className="catalogLayout"><aside className="filterPanel"><h3>Filters</h3><label><span>Category</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All Components</option>{[...new Set(products.map(p=>p.categorySlug))].map(x=><option key={x} value={x}>{products.find(p=>p.categorySlug===x)?.category}</option>)}</select></label><label className="checkLine"><input type="checkbox" checked={onlyStock} onChange={e=>setOnlyStock(e.target.checked)}/> Ready stock only</label><label><span>Maximum price</span><input type="range" min="250000" max="20000000" step="250000" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/><b>{money(maxPrice)}</b></label><p>{list.length} products</p></aside><div><div className="commerceGrid">{list.map(p=><ProductCard key={p.id} p={p} wished={store.wish.includes(p.id)} onWish={()=>store.toggleWish(p.id)} onAdd={()=>store.add(p.id)}/>)}</div>{!list.length&&<div className="emptyState">No products match these filters.</div>}</div></div></>
}

function SearchPage({store}:{store:ReturnType<typeof useStore>}){const[q,setQ]=useState("");const results=useMemo(()=>q.trim()?products.filter(p=>productMatches(p,q)).slice(0,8):products.slice(0,6),[q]);return <section className="contentSection commerceSection"><div className="searchHero"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search GPU, DDR5, 850W, 180Hz..."/></div>{q&&<div className="autosuggest"><span>Suggestions:</span>{products.filter(p=>productMatches(p,q)).slice(0,5).map(p=><Link key={p.id} href={`/product/${p.slug}`}>{p.name}</Link>)}</div>}<div className="commerceGrid">{results.map(p=><ProductCard key={p.id} p={p} wished={store.wish.includes(p.id)} onWish={()=>store.toggleWish(p.id)} onAdd={()=>store.add(p.id)}/>)}</div></section>}

function ProductPage({slug,store}:{slug:string;store:ReturnType<typeof useStore>}){const p=bySlug(slug)||products[0];const[variant,setVariant]=useState<Record<string,string>>(()=>Object.fromEntries((p.variants||[]).map(v=>[v.name,v.values[0]])));return <section className="productCommerce"><div className="detailGrid"><div className="productGallery"><div className="productStage hasImage"><img src={p.image} alt={p.name}/></div><div className="thumbRow imageThumbs">{["Front","Detail","Box","Installed"].map(x=><span key={x}><img src={p.image} alt={`${p.name} ${x}`}/><b>{x}</b></span>)}</div></div><div className="buyBox"><div className="rating big"><Star fill="currentColor"/> {p.rating} · {p.reviews} reviews</div><h1>{p.name}</h1><p>{p.description}</p><p className="price">{money(p.price)}</p>{p.oldPrice&&<del>{money(p.oldPrice)}</del>}<p className={p.stock<5?"stock low":"stock"}>{p.stock>0?`${p.stock} units in stock`:"Out of stock"}</p>{(p.variants||[]).map(v=><div className="variant" key={v.name}><b>{v.name}</b><div>{v.values.map(x=><button className={variant[v.name]===x?"selected":""} onClick={()=>setVariant(s=>({...s,[v.name]:x}))} key={x}>{x}</button>)}</div></div>)}<button disabled={!p.stock} onClick={()=>store.add(p.id,variant)}>Add to Cart</button><Link className="checkoutNow" href="/checkout">Buy Now</Link><button className="secondary" onClick={()=>store.toggleWish(p.id)}>{store.wish.includes(p.id)?"Remove from Wishlist":"Add to Wishlist"}</button><div className="benefits"><span><ShieldCheck/>Original warranty</span><span><Truck/>Fast delivery</span></div></div></div><div className="contentSection"><h2>Specifications</h2><div className="specTable">{Object.entries(p.specs).map(([k,v])=><span key={k}>{k}<b>{v}</b></span>)}</div><h2>Related components</h2><div className="commerceGrid">{products.filter(x=>x.id!==p.id).slice(0,4).map(x=><ProductCard key={x.id} p={x} wished={store.wish.includes(x.id)} onWish={()=>store.toggleWish(x.id)} onAdd={()=>store.add(x.id)}/>)}</div></div></section>}

function CartPage({store}:{store:ReturnType<typeof useStore>}){const lines=store.cart.map(l=>({l,p:products.find(p=>p.id===l.id)})).filter(x=>x.p) as {l:CartLine,p:Product}[];const subtotal=lines.reduce((s,x)=>s+x.p.price*x.l.qty,0);return <section className="contentSection checkoutLayout"><div><h2>Shopping Cart</h2>{lines.length?lines.map(({l,p})=><div className="cartLine" key={p.id}><img src={p.image} alt={p.name}/><div><Link href={`/product/${p.slug}`}><b>{p.name}</b></Link><span>{money(p.price)}</span><div className="qtyCtrl"><button onClick={()=>store.qty(p.id,l.qty-1)}><Minus size={14}/></button><b>{l.qty}</b><button onClick={()=>store.qty(p.id,l.qty+1)}><Plus size={14}/></button></div></div><strong>{money(p.price*l.qty)}</strong><button onClick={()=>store.remove(p.id)}><Trash2 size={18}/></button></div>):<div className="emptyState">Your cart is empty. <Link href="/category/all">Shop components</Link></div>}</div><aside className="orderSummary"><h3>Order Summary</h3><span>Subtotal<b>{money(subtotal)}</b></span><span>Shipping<b>{subtotal>=3000000?"FREE":"Rp 50.000"}</b></span><span>Total<b>{money(subtotal+(subtotal&&subtotal<3000000?50000:0))}</b></span><Link href={lines.length?"/checkout":"/category/all"}>{lines.length?"Proceed to Checkout":"Start Shopping"}</Link></aside></section>}

function WishlistPage({store}:{store:ReturnType<typeof useStore>}){const list=products.filter(p=>store.wish.includes(p.id));return <section className="contentSection commerceSection"><h2>Your Wishlist</h2>{list.length?<div className="commerceGrid">{list.map(p=><ProductCard key={p.id} p={p} wished onWish={()=>store.toggleWish(p.id)} onAdd={()=>store.add(p.id)}/>)}</div>:<div className="emptyState">No saved products yet. Tap the heart on any product.</div>}</section>}

function CheckoutPage({store}:{store:ReturnType<typeof useStore>}){const[placed,setPlaced]=useState(false);const[method,setMethod]=useState("bank");const subtotal=store.cart.reduce((s,l)=>{const p=products.find(p=>p.id===l.id);return s+(p?p.price*l.qty:0)},0);if(placed)return <section className="contentSection successOrder"><CheckCircle2 size={58}/><h2>Order created</h2><p>Your NEXRIG order has been created in this demo flow. Payment gateway integration comes next.</p><Link href="/">Back to Home</Link></section>;return <section className="contentSection checkoutLayout"><form className="checkoutForm" onSubmit={e=>{e.preventDefault();if(store.cart.length){setPlaced(true);store.setCart([])}}}><h2>Checkout</h2><div className="formGrid"><label>Full name<input required placeholder="Your full name"/></label><label>Phone<input required placeholder="08xxxxxxxxxx"/></label><label className="wide">Address<textarea required placeholder="Street, district, city, postal code"/></label><label>City<input required/></label><label>Postal code<input required/></label></div><h3>Payment method</h3><label className="paymentOption"><input type="radio" name="pay" checked={method==="bank"} onChange={()=>setMethod("bank")}/> Bank Transfer</label><label className="paymentOption"><input type="radio" name="pay" checked={method==="va"} onChange={()=>setMethod("va")}/> Virtual Account</label><label className="paymentOption"><input type="radio" name="pay" checked={method==="card"} onChange={()=>setMethod("card")}/> Credit / Debit Card</label><button className="placeOrder" disabled={!store.cart.length}>Place Order</button></form><aside className="orderSummary"><h3>Your Order</h3>{store.cart.map(l=>{const p=products.find(p=>p.id===l.id);return p?<span key={p.id}>{p.name} × {l.qty}<b>{money(p.price*l.qty)}</b></span>:null})}<span>Total<b>{money(subtotal)}</b></span></aside></section>}

function isCompatible(builder:BuilderState){const cpu=products.find(p=>p.id===builder.processor),mb=products.find(p=>p.id===builder.motherboard),ram=products.find(p=>p.id===builder.memory),gpu=products.find(p=>p.id===builder.gpu),psu=products.find(p=>p.id===builder.psu),pcase=products.find(p=>p.id===builder.case),cool=products.find(p=>p.id===builder.cooling);const issues:string[]=[];if(cpu&&mb&&cpu.specs.Socket!==mb.specs.Socket)issues.push("CPU socket does not match motherboard.");if(ram&&mb&&ram.specs.Type!==mb.specs.Memory)issues.push("Memory generation does not match motherboard.");if(gpu&&psu&&Number(psu.specs.Wattage.replace(/\D/g,""))<850)issues.push("Selected GPU requires at least 850W PSU.");if(gpu&&pcase&&Number(pcase.specs.GPUClearance.replace(/\D/g,""))<Number(gpu.specs.Length.replace(/\D/g,"")))issues.push("GPU is too long for the selected case.");if(cool&&cpu&&!cool.specs.Sockets.includes(cpu.specs.Socket))issues.push("CPU cooler does not support selected CPU socket.");return issues}
function BuilderPage({store}:{store:ReturnType<typeof useStore>}){const slots=[['processor','Processor'],['motherboard','Motherboard'],['memory','Memory'],['gpu','Graphics Card'],['storage','Storage'],['psu','Power Supply'],['case','Gaming Case'],['cooling','Cooling'],['monitor','Monitor']] as const;const issues=isCompatible(store.builder);const total=Object.values(store.builder).reduce((s,id)=>{const p=products.find(p=>p.id===id);return s+(p?.price||0)},0);return <section className="contentSection builderEngine"><div className="builderHead"><div><span className="kicker">PC COMPATIBILITY ENGINE</span><h2>Build your NEXRIG</h2></div><strong>{money(total)}</strong></div>{issues.length?<div className="compat bad"><AlertTriangle/>{issues.map(x=><span key={x}>{x}</span>)}</div>:<div className="compat good"><CheckCircle2/>Current selections are compatible.</div>}<div className="builderSlotGrid">{slots.map(([key,label])=>{const candidates=products.filter(p=>key==='gpu'?p.categorySlug==='graphics-card':key==='case'?p.categorySlug==='gaming-case':p.categorySlug===key);const selected=products.find(p=>p.id===store.builder[key]);return <div className="builderSlot" key={key}><b>{label}</b>{selected&&<div className="builderSelected"><img src={selected.image}/><span>{selected.name}</span></div>}<select value={store.builder[key]||""} onChange={e=>store.setBuilder(b=>({...b,[key]:e.target.value||undefined}))}><option value="">Select {label}</option>{candidates.map(p=><option value={p.id} key={p.id}>{p.name} · {money(p.price)}</option>)}</select></div>})}</div><button className="addBuild" disabled={issues.length>0||Object.keys(store.builder).length<4} onClick={()=>Object.values(store.builder).forEach(id=>id&&store.add(id))}>Add compatible build to cart</button></section>}

export default function CommerceEngine({mode,slug}:{mode:string;slug?:string}){const store=useStore();const cartCount=store.cart.reduce((s,x)=>s+x.qty,0);return <main><Header cartCount={cartCount} wishCount={store.wish.length}/>{mode==="category"&&<section className="contentSection commerceSection"><div className="pageTitle"><span className="kicker">SHOP COMPONENTS</span><h1>{slug==="all"?"All Gaming Components":products.find(p=>p.categorySlug===slug)?.category||"Gaming Components"}</h1></div><FilterableCatalog initialCategory={slug||"all"} store={store}/></section>}{mode==="search"&&<SearchPage store={store}/>} {mode==="product"&&<ProductPage slug={slug||products[0].slug} store={store}/>} {mode==="cart"&&<CartPage store={store}/>} {mode==="wishlist"&&<WishlistPage store={store}/>} {mode==="checkout"&&<CheckoutPage store={store}/>} {mode==="builder"&&<BuilderPage store={store}/>}<nav className="bottomNav"><Link href="/">Home</Link><Link href="/category/all">Categories</Link><Link href="/search">Search</Link><Link href="/wishlist">Wishlist</Link><Link href="/cart">Cart</Link></nav></main>}
