export type Product={
  id:string;slug:string;name:string;category:string;categorySlug:string;brand:string;price:number;oldPrice?:number;rating:number;reviews:number;stock:number;image:string;badge?:string;
  specs:Record<string,string>;variants?:{name:string;values:string[]}[];compat?:Record<string,string[]>;description:string;
};

export const products:Product[]=[
{id:"cpu-9800x3d",slug:"amd-ryzen-7-9800x3d",name:"AMD Ryzen 7 9800X3D",category:"Processor",categorySlug:"processor",brand:"AMD",price:8799000,oldPrice:9299000,rating:4.9,reviews:128,stock:12,image:"/api/media/products/processor/amd-ryzen-7-9800x3d.jpg",badge:"BEST SELLER",description:"High-performance gaming processor with 3D V-Cache for competitive and AAA workloads.",specs:{Socket:"AM5",Cores:"8",Threads:"16",TDP:"120W",Memory:"DDR5"},compat:{socket:["AM5"],memory:["DDR5"]}},
{id:"gpu-64cor3",slug:"rtx-64-cor3-gaming-gpu",name:"RTX 64 COR3 Gaming GPU",category:"Graphics Card",categorySlug:"graphics-card",brand:"NEXRIG",price:17999000,oldPrice:18999000,rating:4.8,reviews:91,stock:7,image:"/api/media/products/gpu/rtx-64-cor3-gaming-gpu.jpg",badge:"HOT",description:"High-end graphics platform for high refresh-rate gaming and immersive RPG worlds.",specs:{VRAM:"16GB",Interface:"PCIe 4.0",Power:"320W",PSU:"850W recommended",Length:"330mm"},compat:{psu:["850W","1000W"],case:["ATX","E-ATX"]}},
{id:"ram-64",slug:"nexrig-ddr5-rgb-64-cor3",name:"NEXRIG DDR5 RGB 64 COR3",category:"Memory",categorySlug:"memory",brand:"NEXRIG",price:3199000,oldPrice:3499000,rating:4.7,reviews:73,stock:23,image:"/api/media/products/memory/nexrig-ddr5-rgb-64-cor3.jpg",badge:"NEW",description:"64GB DDR5 RGB memory kit tuned for modern gaming and creator builds.",specs:{Type:"DDR5",Capacity:"64GB",Speed:"6000MT/s",Kit:"2x32GB",RGB:"Yes"},variants:[{name:"Capacity",values:["32GB","64GB"]},{name:"Speed",values:["5600MT/s","6000MT/s"]}],compat:{memory:["DDR5"]}},
{id:"mb-x870",slug:"x870-gaming-wifi",name:"X870 Gaming WiFi",category:"Motherboard",categorySlug:"motherboard",brand:"NEXRIG",price:7299000,oldPrice:7799000,rating:4.6,reviews:58,stock:9,image:"/api/media/products/motherboard/x870-gaming-wifi.jpg",badge:"PRO PICK",description:"X870 gaming motherboard with WiFi and next-generation connectivity.",specs:{Socket:"AM5",Chipset:"X870",Memory:"DDR5",FormFactor:"ATX",WiFi:"WiFi 7"},compat:{socket:["AM5"],memory:["DDR5"],case:["ATX","E-ATX"]}},
{id:"ssd-nvme",slug:"nexrig-nvme-ssd-2tb",name:"NEXRIG NVMe SSD 2TB",category:"Storage",categorySlug:"storage",brand:"NEXRIG",price:2299000,oldPrice:2499000,rating:4.8,reviews:110,stock:31,image:"/api/media/products/storage/nvme-ssd.jpg",badge:"FAST",description:"High-speed NVMe storage for fast boot, load times, and game libraries.",specs:{Capacity:"2TB",Interface:"PCIe 4.0 NVMe",Read:"7400MB/s",Write:"6500MB/s",Form:"M.2 2280"},variants:[{name:"Capacity",values:["1TB","2TB","4TB"]}]},
{id:"psu-850",slug:"nexrig-atx-psu-850w-gold",name:"NEXRIG ATX PSU 850W Gold",category:"Power Supply",categorySlug:"power-supply",brand:"NEXRIG",price:1999000,oldPrice:2199000,rating:4.8,reviews:84,stock:18,image:"/api/media/products/power-supply/atx-psu.jpg",badge:"GOLD",description:"Efficient 850W modular power supply for performance gaming builds.",specs:{Wattage:"850W",Efficiency:"80+ Gold",Modular:"Fully modular",Standard:"ATX 3.1",Warranty:"10 years"},variants:[{name:"Wattage",values:["750W","850W","1000W"]}],compat:{psu:["850W"]}},
{id:"case-mid",slug:"nexrig-airflow-mid-tower",name:"NEXRIG Airflow Mid Tower",category:"Gaming Case",categorySlug:"gaming-case",brand:"NEXRIG",price:1699000,oldPrice:1899000,rating:4.7,reviews:62,stock:15,image:"/api/media/products/gaming-case/mid-tower-case.jpg",badge:"AIRFLOW",description:"Airflow-focused gaming chassis with tempered glass and generous GPU clearance.",specs:{FormFactor:"ATX Mid Tower",GPUClearance:"360mm",Radiator:"360mm",Fans:"4 included",Panel:"Tempered glass"},compat:{case:["ATX"]}},
{id:"monitor-180",slug:"nexrig-27-qhd-180hz-monitor",name:"NEXRIG 27 QHD 180Hz Monitor",category:"Monitor",categorySlug:"monitor",brand:"NEXRIG",price:4299000,oldPrice:4799000,rating:4.8,reviews:96,stock:13,image:"/api/media/products/monitor/gaming-monitor.jpg",badge:"180HZ",description:"Fast QHD gaming display designed for sharp motion and low-latency play.",specs:{Size:"27 inch",Resolution:"2560x1440",Refresh:"180Hz",Panel:"IPS",Response:"1ms"}},
{id:"cable-hdmi",slug:"nexrig-hdmi-21-cable",name:"NEXRIG HDMI 2.1 Cable",category:"Cable",categorySlug:"cable",brand:"NEXRIG",price:249000,rating:4.7,reviews:143,stock:64,image:"/api/media/products/cable/hdmi-cable.jpg",description:"High-bandwidth HDMI 2.1 cable for high refresh rate and 4K gaming displays.",specs:{Version:"HDMI 2.1",Bandwidth:"48Gbps",Length:"2m",Resolution:"4K 120Hz",HDR:"Yes"},variants:[{name:"Length",values:["1m","2m","3m"]}]},
{id:"cooler-air",slug:"nexrig-tower-cpu-cooler",name:"NEXRIG Tower CPU Cooler",category:"Cooling",categorySlug:"cooling",brand:"NEXRIG",price:899000,oldPrice:999000,rating:4.6,reviews:77,stock:26,image:"/api/media/products/cooling/cpu-air-cooler.jpg",description:"High-capacity tower air cooler for quiet thermal control under gaming loads.",specs:{Sockets:"AM5 / LGA1851",Height:"158mm",Fans:"2x120mm",Heatpipes:"6",TDP:"240W"},compat:{socket:["AM5","LGA1851"],case:["ATX"]}}
];

export const categories=["all","processor","motherboard","graphics-card","memory","storage","power-supply","gaming-case","monitor","cable","cooling"];
export const money=(n:number)=>`Rp ${n.toLocaleString("id-ID")}`;
export const bySlug=(slug:string)=>products.find(p=>p.slug===slug);
