export type Product={
  id:string;slug:string;name:string;category:string;categorySlug:string;brand:string;price:number;oldPrice?:number;rating:number;reviews:number;stock:number;image:string;badge?:string;
  specs:Record<string,string>;variants?:{name:string;values:string[]}[];compat?:Record<string,string[]>;description:string;
};

const img={
 processor:"/api/media/products/processor/amd-ryzen-7-9800x3d.jpg", motherboard:"/api/media/products/motherboard/x870-gaming-wifi.jpg", gpu:"/api/media/products/gpu/rtx-64-cor3-gaming-gpu.jpg", memory:"/api/media/products/memory/nexrig-ddr5-rgb-64-cor3.jpg", storage:"/api/media/products/storage/nvme-ssd.jpg", psu:"/api/media/products/power-supply/atx-psu.jpg", case:"/api/media/products/gaming-case/mid-tower-case.jpg", monitor:"/api/media/products/monitor/gaming-monitor.jpg", cable:"/api/media/products/cable/hdmi-cable.jpg", cooling:"/api/media/products/cooling/cpu-air-cooler.jpg"
};

export const products:Product[]=[
{id:"cpu-9800x3d",slug:"amd-ryzen-7-9800x3d",name:"AMD Ryzen 7 9800X3D",category:"Processor",categorySlug:"processor",brand:"AMD",price:8799000,oldPrice:9299000,rating:4.9,reviews:128,stock:12,image:img.processor,badge:"BEST SELLER",description:"High-performance gaming processor with 3D V-Cache for competitive esports, AAA titles, streaming, and creator workloads.",specs:{Socket:"AM5",Cores:"8",Threads:"16",TDP:"120W",Memory:"DDR5"},compat:{socket:["AM5"],memory:["DDR5"]}},
{id:"cpu-9700x",slug:"amd-ryzen-7-9700x",name:"AMD Ryzen 7 9700X",category:"Processor",categorySlug:"processor",brand:"AMD",price:5899000,oldPrice:6299000,rating:4.8,reviews:86,stock:18,image:img.processor,badge:"GAMING PICK",description:"Efficient eight-core AM5 processor for high-refresh gaming, productivity, and upgrade-friendly DDR5 systems.",specs:{Socket:"AM5",Cores:"8",Threads:"16",TDP:"65W",Memory:"DDR5"},compat:{socket:["AM5"],memory:["DDR5"]}},
{id:"cpu-9600x",slug:"amd-ryzen-5-9600x",name:"AMD Ryzen 5 9600X",category:"Processor",categorySlug:"processor",brand:"AMD",price:3999000,rating:4.7,reviews:74,stock:22,image:img.processor,badge:"VALUE",description:"Six-core AM5 gaming CPU tuned for strong frame rates, low power draw, and modern DDR5 platforms.",specs:{Socket:"AM5",Cores:"6",Threads:"12",TDP:"65W",Memory:"DDR5"},compat:{socket:["AM5"],memory:["DDR5"]}},

{id:"mb-x870",slug:"x870-gaming-wifi",name:"X870 Gaming WiFi",category:"Motherboard",categorySlug:"motherboard",brand:"NEXRIG",price:7299000,oldPrice:7799000,rating:4.6,reviews:58,stock:9,image:img.motherboard,badge:"PRO PICK",description:"X870 gaming motherboard with WiFi 7, DDR5, strong VRM cooling, and next-generation connectivity.",specs:{Socket:"AM5",Chipset:"X870",Memory:"DDR5",FormFactor:"ATX",WiFi:"WiFi 7"},compat:{socket:["AM5"],memory:["DDR5"],case:["ATX","E-ATX"]}},
{id:"mb-b850",slug:"b850-gaming-wifi",name:"B850 Gaming WiFi",category:"Motherboard",categorySlug:"motherboard",brand:"NEXRIG",price:4599000,rating:4.7,reviews:64,stock:16,image:img.motherboard,badge:"SWEET SPOT",description:"Feature-rich AM5 motherboard for mainstream gaming builds with DDR5, WiFi, PCIe expansion, and clean cable routing.",specs:{Socket:"AM5",Chipset:"B850",Memory:"DDR5",FormFactor:"ATX",WiFi:"WiFi 6E"},compat:{socket:["AM5"],memory:["DDR5"],case:["ATX","E-ATX"]}},
{id:"mb-b650m",slug:"b650m-compact-wifi",name:"B650M Compact WiFi",category:"Motherboard",categorySlug:"motherboard",brand:"NEXRIG",price:3299000,rating:4.6,reviews:47,stock:19,image:img.motherboard,badge:"COMPACT",description:"Compact AM5 micro-ATX motherboard for efficient gaming systems and smaller airflow-focused cases.",specs:{Socket:"AM5",Chipset:"B650",Memory:"DDR5",FormFactor:"mATX",WiFi:"WiFi 6"},compat:{socket:["AM5"],memory:["DDR5"],case:["mATX","ATX"]}},

{id:"gpu-64cor3",slug:"rtx-64-cor3-gaming-gpu",name:"RTX 64 COR3 Gaming GPU",category:"Graphics Card",categorySlug:"graphics-card",brand:"NEXRIG",price:17999000,oldPrice:18999000,rating:4.8,reviews:91,stock:7,image:img.gpu,badge:"HOT",description:"High-end graphics platform for high refresh-rate gaming, ray-traced visuals, and immersive RPG worlds.",specs:{VRAM:"16GB",Interface:"PCIe 4.0",Power:"320W",PSU:"850W recommended",Length:"330mm"},compat:{psu:["850W","1000W"],case:["ATX","E-ATX"]}},
{id:"gpu-48cor3",slug:"rtx-48-cor3-gaming-gpu",name:"RTX 48 COR3 Gaming GPU",category:"Graphics Card",categorySlug:"graphics-card",brand:"NEXRIG",price:11999000,oldPrice:12999000,rating:4.8,reviews:79,stock:11,image:img.gpu,badge:"1440P",description:"Balanced high-performance GPU for 1440p ultra settings and high refresh-rate competitive gaming.",specs:{VRAM:"12GB",Interface:"PCIe 4.0",Power:"245W",PSU:"750W recommended",Length:"315mm"},compat:{psu:["750W","850W","1000W"],case:["ATX","E-ATX"]}},
{id:"gpu-32cor3",slug:"rtx-32-cor3-gaming-gpu",name:"RTX 32 COR3 Gaming GPU",category:"Graphics Card",categorySlug:"graphics-card",brand:"NEXRIG",price:7999000,rating:4.7,reviews:66,stock:14,image:img.gpu,badge:"1080P+",description:"Strong performance-per-rupiah graphics card for esports, 1080p ultra, and entry 1440p gaming.",specs:{VRAM:"8GB",Interface:"PCIe 4.0",Power:"180W",PSU:"650W recommended",Length:"290mm"},compat:{psu:["650W","750W","850W"],case:["mATX","ATX","E-ATX"]}},

{id:"ram-64",slug:"nexrig-ddr5-rgb-64-cor3",name:"NEXRIG DDR5 RGB 64 COR3",category:"Memory",categorySlug:"memory",brand:"NEXRIG",price:3199000,oldPrice:3499000,rating:4.7,reviews:73,stock:23,image:img.memory,badge:"NEW",description:"64GB DDR5 RGB memory kit tuned for modern gaming, streaming, simulation, and creator builds.",specs:{Type:"DDR5",Capacity:"64GB",Speed:"6000MT/s",Kit:"2x32GB",RGB:"Yes"},variants:[{name:"Capacity",values:["32GB","64GB"]},{name:"Speed",values:["5600MT/s","6000MT/s"]}],compat:{memory:["DDR5"]}},
{id:"ram-32",slug:"nexrig-ddr5-rgb-32gb",name:"NEXRIG DDR5 RGB 32GB",category:"Memory",categorySlug:"memory",brand:"NEXRIG",price:1899000,oldPrice:2099000,rating:4.8,reviews:119,stock:41,image:img.memory,badge:"BEST VALUE",description:"Fast 32GB dual-channel DDR5 kit for gaming, multitasking, and balanced enthusiast systems.",specs:{Type:"DDR5",Capacity:"32GB",Speed:"6000MT/s",Kit:"2x16GB",RGB:"Yes"},compat:{memory:["DDR5"]}},
{id:"ram-32-stealth",slug:"nexrig-ddr5-stealth-32gb",name:"NEXRIG DDR5 Stealth 32GB",category:"Memory",categorySlug:"memory",brand:"NEXRIG",price:1599000,rating:4.7,reviews:84,stock:35,image:img.memory,badge:"STEALTH",description:"Low-profile 32GB DDR5 kit for clean black builds and compact CPU cooler clearance.",specs:{Type:"DDR5",Capacity:"32GB",Speed:"5600MT/s",Kit:"2x16GB",RGB:"No"},compat:{memory:["DDR5"]}},

{id:"ssd-nvme",slug:"nexrig-nvme-ssd-2tb",name:"NEXRIG NVMe SSD 2TB",category:"Storage",categorySlug:"storage",brand:"NEXRIG",price:2299000,oldPrice:2499000,rating:4.8,reviews:110,stock:31,image:img.storage,badge:"FAST",description:"High-speed PCIe 4.0 NVMe storage for rapid boot times, large game libraries, and creator caches.",specs:{Capacity:"2TB",Interface:"PCIe 4.0 NVMe",Read:"7400MB/s",Write:"6500MB/s",Form:"M.2 2280"},variants:[{name:"Capacity",values:["1TB","2TB","4TB"]}]},
{id:"ssd-1tb",slug:"nexrig-nvme-ssd-1tb",name:"NEXRIG NVMe SSD 1TB",category:"Storage",categorySlug:"storage",brand:"NEXRIG",price:1299000,rating:4.7,reviews:138,stock:48,image:img.storage,badge:"POPULAR",description:"Fast 1TB NVMe SSD for Windows, competitive games, and everyday high-speed storage.",specs:{Capacity:"1TB",Interface:"PCIe 4.0 NVMe",Read:"7000MB/s",Write:"5800MB/s",Form:"M.2 2280"}},
{id:"ssd-4tb",slug:"nexrig-nvme-ssd-4tb",name:"NEXRIG NVMe SSD 4TB",category:"Storage",categorySlug:"storage",brand:"NEXRIG",price:4499000,rating:4.9,reviews:52,stock:10,image:img.storage,badge:"4TB",description:"Large-capacity 4TB high-speed NVMe drive for massive AAA libraries, media, and workstation files.",specs:{Capacity:"4TB",Interface:"PCIe 4.0 NVMe",Read:"7400MB/s",Write:"6800MB/s",Form:"M.2 2280"}},

{id:"psu-850",slug:"nexrig-atx-psu-850w-gold",name:"NEXRIG ATX PSU 850W Gold",category:"Power Supply",categorySlug:"power-supply",brand:"NEXRIG",price:1999000,oldPrice:2199000,rating:4.8,reviews:84,stock:18,image:img.psu,badge:"80+ GOLD",description:"Efficient fully modular 850W ATX 3.1 power supply for high-performance gaming builds.",specs:{Wattage:"850W",Efficiency:"80+ Gold",Modular:"Fully modular",Standard:"ATX 3.1",Warranty:"10 years"},variants:[{name:"Wattage",values:["750W","850W","1000W"]}],compat:{psu:["850W"]}},
{id:"psu-750",slug:"nexrig-atx-psu-750w-gold",name:"NEXRIG ATX PSU 750W Gold",category:"Power Supply",categorySlug:"power-supply",brand:"NEXRIG",price:1699000,rating:4.7,reviews:76,stock:24,image:img.psu,badge:"BALANCED",description:"750W Gold-rated modular PSU for efficient mid-to-high-end gaming systems.",specs:{Wattage:"750W",Efficiency:"80+ Gold",Modular:"Fully modular",Standard:"ATX 3.1",Warranty:"8 years"},compat:{psu:["750W"]}},
{id:"psu-1000",slug:"nexrig-atx-psu-1000w-gold",name:"NEXRIG ATX PSU 1000W Gold",category:"Power Supply",categorySlug:"power-supply",brand:"NEXRIG",price:2699000,rating:4.9,reviews:61,stock:12,image:img.psu,badge:"HEADROOM",description:"1000W fully modular PSU with generous power headroom for flagship GPUs and upgrade-heavy builds.",specs:{Wattage:"1000W",Efficiency:"80+ Gold",Modular:"Fully modular",Standard:"ATX 3.1",Warranty:"10 years"},compat:{psu:["1000W"]}},

{id:"case-mid",slug:"nexrig-airflow-mid-tower",name:"NEXRIG Airflow Mid Tower",category:"Gaming Case",categorySlug:"gaming-case",brand:"NEXRIG",price:1699000,oldPrice:1899000,rating:4.7,reviews:62,stock:15,image:img.case,badge:"AIRFLOW",description:"Airflow-focused ATX gaming chassis with tempered glass and generous GPU clearance.",specs:{FormFactor:"ATX Mid Tower",GPUClearance:"360mm",Radiator:"360mm",Fans:"4 included",Panel:"Tempered glass"},compat:{case:["ATX"]}},
{id:"case-compact",slug:"nexrig-compact-matx-case",name:"NEXRIG Compact mATX Case",category:"Gaming Case",categorySlug:"gaming-case",brand:"NEXRIG",price:1299000,rating:4.7,reviews:43,stock:21,image:img.case,badge:"COMPACT",description:"Compact micro-ATX gaming case with mesh airflow and tidy cable-management channels.",specs:{FormFactor:"mATX Tower",GPUClearance:"330mm",Radiator:"240mm",Fans:"3 included",Panel:"Tempered glass"},compat:{case:["mATX"]}},
{id:"case-show",slug:"nexrig-panoramic-showcase",name:"NEXRIG Panoramic Showcase",category:"Gaming Case",categorySlug:"gaming-case",brand:"NEXRIG",price:2499000,rating:4.8,reviews:48,stock:9,image:img.case,badge:"SHOW BUILD",description:"Dual-glass panoramic chassis designed for RGB showcase builds with large radiators and flagship GPUs.",specs:{FormFactor:"ATX Mid Tower",GPUClearance:"400mm",Radiator:"360mm",Fans:"6 supported",Panel:"Dual tempered glass"},compat:{case:["ATX","E-ATX"]}},

{id:"monitor-180",slug:"nexrig-27-qhd-180hz-monitor",name:"NEXRIG 27 QHD 180Hz Monitor",category:"Monitor",categorySlug:"monitor",brand:"NEXRIG",price:4299000,oldPrice:4799000,rating:4.8,reviews:96,stock:13,image:img.monitor,badge:"180HZ",description:"Fast 27-inch QHD IPS gaming display designed for sharp motion, rich detail, and low-latency play.",specs:{Size:"27 inch",Resolution:"2560x1440",Refresh:"180Hz",Panel:"IPS",Response:"1ms"}},
{id:"monitor-240",slug:"nexrig-25-fhd-240hz-monitor",name:"NEXRIG 25 FHD 240Hz Monitor",category:"Monitor",categorySlug:"monitor",brand:"NEXRIG",price:3699000,rating:4.8,reviews:82,stock:17,image:img.monitor,badge:"240HZ",description:"Competitive 240Hz gaming display for fast FPS, racing, and esports titles.",specs:{Size:"25 inch",Resolution:"1920x1080",Refresh:"240Hz",Panel:"Fast IPS",Response:"0.5ms"}},
{id:"monitor-4k",slug:"nexrig-32-4k-144hz-monitor",name:"NEXRIG 32 4K 144Hz Monitor",category:"Monitor",categorySlug:"monitor",brand:"NEXRIG",price:8999000,oldPrice:9499000,rating:4.9,reviews:44,stock:6,image:img.monitor,badge:"4K 144HZ",description:"Large 32-inch 4K high-refresh display for premium AAA gaming, simulation, and creative work.",specs:{Size:"32 inch",Resolution:"3840x2160",Refresh:"144Hz",Panel:"IPS",Response:"1ms"}},

{id:"cable-hdmi",slug:"nexrig-hdmi-21-cable",name:"NEXRIG HDMI 2.1 Cable",category:"Cable",categorySlug:"cable",brand:"NEXRIG",price:249000,rating:4.7,reviews:143,stock:64,image:img.cable,badge:"48GBPS",description:"High-bandwidth HDMI 2.1 cable for 4K 120Hz, HDR, gaming monitors, TVs, and consoles.",specs:{Version:"HDMI 2.1",Bandwidth:"48Gbps",Length:"2m",Resolution:"4K 120Hz",HDR:"Yes"},variants:[{name:"Length",values:["1m","2m","3m"]}]},
{id:"cable-dp",slug:"nexrig-displayport-21-cable",name:"NEXRIG DisplayPort 2.1 Cable",category:"Cable",categorySlug:"cable",brand:"NEXRIG",price:299000,rating:4.8,reviews:91,stock:52,image:img.cable,badge:"DP 2.1",description:"High-bandwidth DisplayPort cable for high-refresh QHD and 4K gaming monitor setups.",specs:{Version:"DisplayPort 2.1",Length:"2m",Resolution:"4K High Refresh",HDR:"Yes",Shielding:"Braided"}},
{id:"cable-kit",slug:"nexrig-sleeved-cable-kit",name:"NEXRIG Sleeved PSU Cable Kit",category:"Cable",categorySlug:"cable",brand:"NEXRIG",price:649000,rating:4.7,reviews:38,stock:27,image:img.cable,badge:"BUILD STYLE",description:"Braided extension cable kit for cleaner cable routing and premium showcase PC aesthetics.",specs:{Type:"PSU Extension",Color:"Black",Pieces:"6",Combs:"Included",Sleeve:"Braided"}},

{id:"cooler-air",slug:"nexrig-tower-cpu-cooler",name:"NEXRIG Tower CPU Cooler",category:"Cooling",categorySlug:"cooling",brand:"NEXRIG",price:899000,oldPrice:999000,rating:4.6,reviews:77,stock:26,image:img.cooling,badge:"QUIET",description:"High-capacity tower air cooler for quiet thermal control under sustained gaming and creator workloads.",specs:{Sockets:"AM5 / LGA1851",Height:"158mm",Fans:"2x120mm",Heatpipes:"6",TDP:"240W"},compat:{socket:["AM5","LGA1851"],case:["ATX"]}},
{id:"cooler-aio240",slug:"nexrig-aio-240-rgb",name:"NEXRIG AIO 240 RGB",category:"Cooling",categorySlug:"cooling",brand:"NEXRIG",price:1599000,rating:4.7,reviews:69,stock:18,image:img.cooling,badge:"AIO",description:"240mm liquid cooler with quiet pump tuning and addressable RGB lighting for gaming builds.",specs:{Sockets:"AM5 / LGA1851",Radiator:"240mm",Fans:"2x120mm",Pump:"PWM",RGB:"ARGB"},compat:{socket:["AM5","LGA1851"],case:["mATX","ATX","E-ATX"]}},
{id:"cooler-aio360",slug:"nexrig-aio-360-lcd",name:"NEXRIG AIO 360 LCD",category:"Cooling",categorySlug:"cooling",brand:"NEXRIG",price:2699000,rating:4.9,reviews:54,stock:8,image:img.cooling,badge:"LCD",description:"Flagship 360mm liquid cooler with LCD pump display for premium high-TDP gaming processors.",specs:{Sockets:"AM5 / LGA1851",Radiator:"360mm",Fans:"3x120mm",Display:"LCD",RGB:"ARGB"},compat:{socket:["AM5","LGA1851"],case:["ATX","E-ATX"]}}
];

export const categories=["all","processor","motherboard","graphics-card","memory","storage","power-supply","gaming-case","monitor","cable","cooling"];
export const money=(n:number)=>`Rp ${n.toLocaleString("id-ID")}`;
export const bySlug=(slug:string)=>products.find(p=>p.slug===slug);
