import Link from "next/link";
import { Star, ShoppingCart, ShieldCheck, Truck, Cpu, CircuitBoard, MemoryStick, HardDrive, Zap, Box, Monitor } from "lucide-react";

const demoProducts = [
  { name:"AMD Ryzen 7 9800X3D", cat:"Processor", price:"Rp 8.799.000", img:"/api/media/products/processor/amd-ryzen-7-9800x3d.jpg" },
  { name:"RTX 64 COR3 Gaming GPU", cat:"Graphics Card", price:"Rp 17.999.000", img:"/api/media/products/gpu/rtx-64-cor3-gaming-gpu.jpg" },
  { name:"NEXRIG DDR5 RGB 64 COR3", cat:"Memory", price:"Rp 3.199.000", img:"/api/media/products/memory/nexrig-ddr5-rgb-64-cor3.jpg" },
  { name:"X870 Gaming WiFi", cat:"Motherboard", price:"Rp 7.299.000", img:"/api/media/products/motherboard/x870-gaming-wifi.jpg" }
];

const humanize=(s:string)=>s.replace(/-/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const productSlug=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");

function imageForProduct(title:string){
  const t=title.toLowerCase();
  if(t.includes("gpu")||t.includes("rtx")||t.includes("graphics")) return demoProducts[1].img;
  if(t.includes("memory")||t.includes("ddr")||t.includes("ram")) return demoProducts[2].img;
  if(t.includes("motherboard")||t.includes("x870")) return demoProducts[3].img;
  return demoProducts[0].img;
}

function ProductGrid(){return <div className="productGrid innerGrid">{demoProducts.map((p,i)=><Link className="card" href={`/product/${productSlug(p.name)}`} key={p.name}><div className="productImage"><img src={p.img} alt={p.name} loading="lazy"/><span className="miniBadge">{i<2?"POPULAR":"NEXRIG PICK"}</span></div><div className="cat">{p.cat}</div><h3>{p.name}</h3><div className="rating"><Star size={14} fill="currentColor"/> 4.{9-i}</div><strong>{p.price}</strong></Link>)}</div>}

function Shell({title,kicker="NEXRIG",children}:{title:string;kicker?:string;children:React.ReactNode}){return <main><header className="topbar"><Link href="/" className="brand">NEX<span>RIG</span></Link><Link href="/cart"><ShoppingCart size={21}/></Link></header><div className="pageHero"><span className="kicker">{kicker}</span><h1>{title}</h1><p>Performance-first PC components, compatibility guidance, official warranty, and expert support for your next gaming rig.</p></div>{children}<div className="pageLinks"><Link href="/">Home</Link><Link href="/category/all">All Components</Link><Link href="/builder">PC Builder</Link><Link href="/guides/build-gaming-pc">Guides</Link></div></main>}

export default async function CatchAll({params}:{params:Promise<{slug:string[]}>}){
 const {slug}=await params; const [type,...rest]=slug; const leaf=rest.join("-")||"all"; const title=humanize(leaf); const mainImage=imageForProduct(title);
 if(type==="product") return <Shell title={title} kicker="PRODUCT DETAIL"><div className="detailGrid"><section className="productGallery"><div className="productStage hasImage"><img src={mainImage} alt={title}/></div><div className="thumbRow imageThumbs"><span><img src={mainImage} alt={`${title} front`}/><b>Front</b></span><span><img src={demoProducts[3].img} alt="Component detail"/><b>Detail</b></span><span><img src={demoProducts[0].img} alt="Retail box"/><b>Box</b></span><span><img src={demoProducts[1].img} alt="Installed gaming PC"/><b>Installed</b></span></div></section><section className="buyBox"><div className="rating big"><Star fill="currentColor"/> 4.9 · 128 reviews</div><h2>{title}</h2><p className="price">Rp 8.799.000</p><p className="stock">In stock · Official warranty</p><button>Add to Cart</button><button className="secondary">Buy Now</button><div className="benefits"><span><ShieldCheck/> Original</span><span><Truck/> Fast delivery</span></div></section></div><section className="contentSection"><h2>Product details</h2><p>Built for high-performance gaming, streaming, content creation, and stable long-session workloads. Every NEXRIG listing includes compatibility guidance before checkout.</p><div className="specTable"><span>Category<b>{humanize(title.includes("Gpu")?"graphics card":"gaming component")}</b></span><span>Warranty<b>Official distributor</b></span><span>Condition<b>100% new</b></span><span>Support<b>Pre-build consultation</b></span></div><h2>Compatible & related components</h2><ProductGrid/></section></Shell>;
 if(type==="builder") return <Shell title="Build Your Dream PC" kicker="COMPATIBILITY ENGINE"><section className="contentSection"><div className="builderSteps">{[[Cpu,"1. Processor"],[CircuitBoard,"2. Motherboard"],[MemoryStick,"3. Memory"],[HardDrive,"4. Storage"],[Zap,"5. Power Supply"],[Box,"6. Case"],[Monitor,"7. Monitor"]].map(([Icon,label]:any)=><Link href="/category/all" key={label}><Icon/><b>{label}</b><span>Select a compatible part</span></Link>)}</div><h2>Recommended starting points</h2><ProductGrid/></section></Shell>;
 if(type==="search") return <Shell title="Search NEXRIG" kicker="FIND YOUR GEAR"><section className="contentSection"><div className="fakeSearch">Search processor, GPU, motherboard, RAM, SSD...</div><h2>Popular searches</h2><div className="chips"><Link href="/category/processor">Ryzen Gaming</Link><Link href="/category/graphics-card">Gaming GPU</Link><Link href="/category/memory">DDR5 RAM</Link><Link href="/gaming-pc/high-end">High-End Build</Link></div><ProductGrid/></section></Shell>;
 if(type==="wishlist") return <Shell title="Your Wishlist" kicker="SAVED GEAR"><section className="contentSection"><p>Your saved gaming components stay one tap away. Start with these popular NEXRIG picks.</p><ProductGrid/></section></Shell>;
 if(type==="cart") return <Shell title="Shopping Cart" kicker="READY TO BUILD"><section className="contentSection"><div className="cartMock"><div><b>Your cart is ready for components.</b><p>Add compatible parts and we’ll keep the build path easy to review.</p></div><Link href="/category/all">Continue Shopping</Link></div><h2>Frequently bought together</h2><ProductGrid/></section></Shell>;
 if(type==="guides") return <Shell title={title} kicker="NEXRIG GUIDE"><article className="contentSection article"><p>Choosing the right PC component starts with your target game, resolution, refresh rate, budget, and upgrade path.</p><h2>Start with your performance target</h2><p>For competitive gaming, prioritize stable frame rates and low latency. For cinematic RPG and open-world games, balance GPU performance, memory capacity, fast storage, and cooling.</p><h2>Check compatibility before checkout</h2><p>Match processor socket, motherboard chipset, memory generation, case clearance, cooling requirements, and PSU headroom. NEXRIG’s builder links these decisions so you can move between guides and compatible products.</p><h2>Recommended hardware</h2><ProductGrid/></article></Shell>;
 if(type==="gaming-pc") return <Shell title={`${title} Gaming PC Build`} kicker="CURATED BUILD"><section className="contentSection"><p>A balanced NEXRIG configuration for smooth gaming, strong upgrade potential, and clean component compatibility.</p><div className="buildList">{["Processor","Graphics Card","Motherboard","Memory","NVMe SSD","Power Supply","Gaming Case","Cooling"].map((x,i)=><Link href={`/category/${productSlug(x)}`} key={x}><span>{i+1}</span><b>{x}</b><small>View compatible options →</small></Link>)}</div><ProductGrid/></section></Shell>;
 if(type==="brand") return <Shell title={`${title} Gaming Hardware`} kicker="SHOP BY BRAND"><section className="contentSection"><p>Browse popular {title} components selected for gaming performance, reliability, warranty coverage, and PC-build compatibility.</p><ProductGrid/><h2>Shop related categories</h2><div className="chips"><Link href="/category/processor">Processor</Link><Link href="/category/motherboard">Motherboard</Link><Link href="/category/memory">Memory</Link><Link href="/category/monitor">Monitor</Link></div></section></Shell>;
 return <Shell title={type==="category"?(leaf==="all"?"All Gaming Components":`${title} Gaming`):humanize(slug.join("-"))} kicker={type==="category"?"SHOP COMPONENTS":"NEXRIG STORE"}><section className="contentSection"><p>Explore original gaming hardware with clear specifications, official warranty, compatibility guidance, and internal links to related parts and build guides.</p><div className="filterBar"><span>Popular</span><span>Newest</span><span>Best Rating</span><span>Price</span></div><ProductGrid/><h2>Helpful buying guides</h2><div className="seoGrid"><Link href="/guides/best-gaming-processor">Best Gaming Processors</Link><Link href="/guides/how-to-choose-gpu">How to Choose a GPU</Link><Link href="/gaming-pc/high-end">High-End Gaming Build</Link><Link href="/builder">Check Compatibility</Link></div></section></Shell>;
}
