import Link from "next/link";
import { Star, ShoppingCart, ShieldCheck, Truck, Cpu, CircuitBoard, MemoryStick, HardDrive, Zap, Box, Monitor, Cable, Fan, Heart, SlidersHorizontal } from "lucide-react";

type Product={name:string;cat:string;slug:string;price:string;oldPrice?:string;rating:string;reviews:number;img:string;badge?:string;stock:string;shipping:string};

const products:Product[]=[
  {name:"AMD Ryzen 7 9800X3D",cat:"Processor",slug:"amd-ryzen-7-9800x3d",price:"Rp 8.799.000",oldPrice:"Rp 9.399.000",rating:"4.9",reviews:128,img:"/api/media/products/processor/amd-ryzen-7-9800x3d.jpg",badge:"BEST SELLER",stock:"Ready Stock",shipping:"Ships today"},
  {name:"RTX 64 COR3 Gaming GPU",cat:"Graphics Card",slug:"rtx-64-cor3-gaming-gpu",price:"Rp 17.999.000",rating:"4.8",reviews:96,img:"/api/media/products/gpu/rtx-64-cor3-gaming-gpu.jpg",badge:"HOT",stock:"Ready Stock",shipping:"Free delivery"},
  {name:"NEXRIG DDR5 RGB 64 COR3",cat:"Memory",slug:"nexrig-ddr5-rgb-64-cor3",price:"Rp 3.199.000",oldPrice:"Rp 3.499.000",rating:"4.7",reviews:74,img:"/api/media/products/memory/nexrig-ddr5-rgb-64-cor3.jpg",badge:"DEAL",stock:"Ready Stock",shipping:"Ships today"},
  {name:"X870 Gaming WiFi",cat:"Motherboard",slug:"x870-gaming-wifi",price:"Rp 7.299.000",rating:"4.6",reviews:63,img:"/api/media/products/motherboard/x870-gaming-wifi.jpg",stock:"Ready Stock",shipping:"Official warranty"},
  {name:"NEXRIG NVMe Gen4 2TB",cat:"Storage",slug:"nexrig-nvme-gen4-2tb",price:"Rp 2.499.000",oldPrice:"Rp 2.799.000",rating:"4.8",reviews:88,img:"/api/media/products/storage/nvme-ssd.jpg",badge:"FAST SSD",stock:"Ready Stock",shipping:"Ships today"},
  {name:"NEXRIG 850W Gold PSU",cat:"Power Supply",slug:"nexrig-850w-gold-psu",price:"Rp 2.199.000",rating:"4.7",reviews:55,img:"/api/media/products/power-supply/atx-psu.jpg",badge:"80+ GOLD",stock:"Ready Stock",shipping:"3 year warranty"},
  {name:"NEXRIG Airflow Mid Tower",cat:"Gaming Case",slug:"nexrig-airflow-mid-tower",price:"Rp 1.899.000",rating:"4.8",reviews:71,img:"/api/media/products/gaming-case/mid-tower-case.jpg",badge:"NEW",stock:"Ready Stock",shipping:"Bulky delivery"},
  {name:"NEXRIG 27\" 180Hz Gaming Monitor",cat:"Monitor",slug:"nexrig-27-180hz-gaming-monitor",price:"Rp 4.599.000",oldPrice:"Rp 4.999.000",rating:"4.8",reviews:102,img:"/api/media/products/monitor/gaming-monitor.jpg",badge:"180HZ",stock:"Ready Stock",shipping:"Free delivery"},
  {name:"NEXRIG HDMI 2.1 Ultra Cable",cat:"Cable",slug:"nexrig-hdmi-2-1-ultra-cable",price:"Rp 349.000",rating:"4.7",reviews:146,img:"/api/media/products/cable/hdmi-cable.jpg",stock:"Ready Stock",shipping:"Ships today"},
  {name:"NEXRIG Tower CPU Air Cooler",cat:"Cooling",slug:"nexrig-tower-cpu-air-cooler",price:"Rp 899.000",rating:"4.8",reviews:81,img:"/api/media/products/cooling/cpu-air-cooler.jpg",badge:"QUIET",stock:"Ready Stock",shipping:"Ships today"}
];

const categories=[
  ["Processor","processor",Cpu],["Motherboard","motherboard",CircuitBoard],["Memory","memory",MemoryStick],["Storage","storage",HardDrive],["Power Supply","power-supply",Zap],["Gaming Case","gaming-case",Box],["Monitor","monitor",Monitor],["Cable","cable",Cable],["Cooling","cooling",Fan],["Graphics Card","graphics-card",Cpu]
] as const;

const humanize=(s:string)=>s.replace(/-/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const slugify=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const categorySlug=(cat:string)=>cat==="Graphics Card"?"graphics-card":slugify(cat);

function ProductCard({p}:{p:Product}){return <Link className="commerceCard" href={`/product/${p.slug}`}>
  <div className="commerceImage"><img src={p.img} alt={p.name}/>{p.badge&&<span className="commerceBadge">{p.badge}</span>}<span className="wishDot"><Heart size={16}/></span></div>
  <div className="commerceBody"><span className="commerceCat">{p.cat}</span><h3>{p.name}</h3><div className="commerceRating"><Star size={13} fill="currentColor"/> {p.rating} <small>({p.reviews})</small></div><div className="priceLine"><strong>{p.price}</strong>{p.oldPrice&&<del>{p.oldPrice}</del>}</div><div className="availability"><span>{p.stock}</span><small>{p.shipping}</small></div></div>
</Link>}

function ProductGrid({items=products}:{items?:Product[]}){return <div className="commerceGrid">{items.map(p=><ProductCard key={p.slug} p={p}/>)}</div>}

function Shell({title,kicker="NEXRIG",children}:{title:string;kicker?:string;children:React.ReactNode}){return <main><header className="topbar"><Link href="/" className="brand">NEX<span>RIG</span></Link><Link href="/cart"><ShoppingCart size={21}/></Link></header><div className="pageHero"><span className="kicker">{kicker}</span><h1>{title}</h1><p>Performance-first PC components, compatibility guidance, official warranty, and expert support for your next gaming rig.</p></div>{children}<div className="pageLinks"><Link href="/">Home</Link><Link href="/category/all">All Components</Link><Link href="/builder">PC Builder</Link><Link href="/guides/build-gaming-pc">Guides</Link></div></main>}

export default async function CatchAll({params}:{params:Promise<{slug:string[]}>}){
 const {slug}=await params; const [type,...rest]=slug; const leaf=rest.join("-")||"all"; const title=humanize(leaf);
 const matched=products.find(p=>p.slug===leaf) || products[0];
 if(type==="product") return <Shell title={matched.name} kicker="PRODUCT DETAIL"><div className="detailGrid"><section className="productGallery"><div className="productStage hasImage"><img src={matched.img} alt={matched.name}/></div><div className="thumbRow imageThumbs"><span><img src={matched.img} alt={`${matched.name} front`}/><b>Front</b></span><span><img src={matched.img} alt={`${matched.name} detail`}/><b>Detail</b></span><span><img src={matched.img} alt={`${matched.name} package`}/><b>Box</b></span><span><img src={products[(products.indexOf(matched)+1)%products.length].img} alt="Compatible build"/><b>Installed</b></span></div></section><section className="buyBox"><div className="rating big"><Star fill="currentColor"/> {matched.rating} · {matched.reviews} reviews</div><h2>{matched.name}</h2><p className="price">{matched.price}</p>{matched.oldPrice&&<p className="oldPrice">{matched.oldPrice}</p>}<p className="stock">● {matched.stock}</p><button>Add to Cart</button><button className="secondary">Buy Now</button><div className="benefits"><span><ShieldCheck/> Original</span><span><Truck/> {matched.shipping}</span></div></section></div><section className="contentSection"><h2>Product details</h2><p>Built for high-performance gaming, streaming, content creation, and stable long-session workloads. Every NEXRIG listing includes compatibility guidance before checkout.</p><div className="specTable"><span>Category<b>{matched.cat}</b></span><span>Warranty<b>Official distributor</b></span><span>Condition<b>100% new</b></span><span>Support<b>Pre-build consultation</b></span></div><h2>Compatible & related components</h2><ProductGrid items={products.filter(p=>p.slug!==matched.slug).slice(0,4)}/></section></Shell>;
 if(type==="builder") return <Shell title="Build Your Dream PC" kicker="COMPATIBILITY ENGINE"><section className="contentSection"><div className="builderSteps">{[[Cpu,"1. Processor"],[CircuitBoard,"2. Motherboard"],[MemoryStick,"3. Memory"],[HardDrive,"4. Storage"],[Zap,"5. Power Supply"],[Box,"6. Case"],[Monitor,"7. Monitor"],[Fan,"8. Cooling"]].map(([Icon,label]:any)=><Link href="/category/all" key={label}><Icon/><b>{label}</b><span>Select a compatible part</span></Link>)}</div><h2>Recommended starting points</h2><ProductGrid items={products.slice(0,8)}/></section></Shell>;
 if(type==="search") return <Shell title="Search NEXRIG" kicker="FIND YOUR GEAR"><section className="contentSection"><div className="fakeSearch">Search processor, GPU, motherboard, RAM, SSD, case, monitor...</div><h2>Popular searches</h2><div className="chips"><Link href="/category/processor">Ryzen Gaming</Link><Link href="/category/graphics-card">Gaming GPU</Link><Link href="/category/memory">DDR5 RAM</Link><Link href="/category/storage">NVMe SSD</Link></div><ProductGrid items={products.slice(0,8)}/></section></Shell>;
 if(type==="wishlist") return <Shell title="Your Wishlist" kicker="SAVED GEAR"><section className="contentSection"><p>Your saved gaming components stay one tap away. Start with these popular NEXRIG picks.</p><ProductGrid items={products.slice(0,6)}/></section></Shell>;
 if(type==="cart") return <Shell title="Shopping Cart" kicker="READY TO BUILD"><section className="contentSection"><div className="cartMock"><div><b>Your cart is ready for components.</b><p>Add compatible parts and we’ll keep the build path easy to review.</p></div><Link href="/category/all">Continue Shopping</Link></div><h2>Frequently bought together</h2><ProductGrid items={products.slice(0,4)}/></section></Shell>;
 if(type==="guides") return <Shell title={title} kicker="NEXRIG GUIDE"><article className="contentSection article"><p>Choosing the right PC component starts with your target game, resolution, refresh rate, budget, and upgrade path.</p><h2>Start with your performance target</h2><p>For competitive gaming, prioritize stable frame rates and low latency. For cinematic RPG and open-world games, balance GPU performance, memory capacity, fast storage, cooling, and PSU headroom.</p><h2>Recommended hardware</h2><ProductGrid items={products.slice(0,6)}/></article></Shell>;
 if(type==="gaming-pc") return <Shell title={`${title} Gaming PC Build`} kicker="CURATED BUILD"><section className="contentSection"><p>A balanced NEXRIG configuration for smooth gaming, strong upgrade potential, and clean component compatibility.</p><div className="buildList">{["Processor","Graphics Card","Motherboard","Memory","Storage","Power Supply","Gaming Case","Cooling"].map((x,i)=><Link href={`/category/${categorySlug(x)}`} key={x}><span>{i+1}</span><b>{x}</b><small>View compatible options →</small></Link>)}</div><ProductGrid items={products.slice(0,8)}/></section></Shell>;
 if(type==="brand") return <Shell title={`${title} Gaming Hardware`} kicker="SHOP BY BRAND"><section className="contentSection"><p>Browse gaming components selected for performance, reliability, warranty coverage, and PC-build compatibility.</p><ProductGrid/><h2>Shop related categories</h2><div className="chips"><Link href="/category/processor">Processor</Link><Link href="/category/motherboard">Motherboard</Link><Link href="/category/memory">Memory</Link><Link href="/category/monitor">Monitor</Link></div></section></Shell>;
 if(type==="category"){
   const active=leaf==="all"?"all":leaf;
   const filtered=active==="all"?products:products.filter(p=>categorySlug(p.cat)===active);
   const pageTitle=active==="all"?"All Gaming Components":`${humanize(active)} Gaming`;
   return <Shell title={pageTitle} kicker="SHOP COMPONENTS"><section className="shopCategoryBar"><div className="categoryRail">{categories.map(([label,slug,Icon])=><Link key={slug} href={`/category/${slug}`} className={active===slug?"active":""}><Icon size={18}/><span>{label}</span></Link>)}</div></section><section className="contentSection commerceSection"><div className="catalogToolbar"><div><b>{filtered.length} products</b><span>Original hardware · Official warranty</span></div><button><SlidersHorizontal size={16}/> Filter & Sort</button></div><div className="quickFilters"><span>Ready Stock</span><span>Best Rating</span><span>Free Delivery</span><span>Official Warranty</span><span>Under Rp 5M</span></div><ProductGrid items={filtered}/><div className="catalogTrust"><div><ShieldCheck/><b>100% Original</b><span>Verified distributor stock</span></div><div><Truck/><b>Fast Delivery</b><span>Tracked shipping nationwide</span></div><div><Cpu/><b>Compatibility Check</b><span>Ask before you build</span></div></div><h2>Need help choosing?</h2><div className="seoGrid"><Link href="/guides/best-gaming-processor">Best Gaming Processors</Link><Link href="/guides/how-to-choose-gpu">How to Choose a GPU</Link><Link href="/gaming-pc/high-end">High-End Gaming Build</Link><Link href="/builder">Check Compatibility</Link></div></section></Shell>;
 }
 return <Shell title={humanize(slug.join("-"))} kicker="NEXRIG STORE"><section className="contentSection"><p>Explore original gaming hardware with clear specifications, official warranty, compatibility guidance, and internal links to related parts and build guides.</p><ProductGrid items={products.slice(0,8)}/></section></Shell>;
}
