import Link from "next/link";

const articles:Record<string,{title:string;cat:string;intro:string;sections:{h:string;p:string}[];links:{label:string;href:string}[]}>= {
 "cara-memilih-processor-gaming":{title:"Cara Memilih Processor Gaming: FPS, Core, Cache, dan Upgrade Path",cat:"Processor",intro:"Processor gaming yang tepat bukan selalu model paling mahal. Yang lebih penting adalah target FPS, jenis game, GPU pasangan, thermal, dan upgrade path platform.",sections:[{h:"Mulai dari target game dan FPS",p:"Game kompetitif biasanya sensitif terhadap latency dan performa CPU pada frame rate tinggi. Game AAA lebih sering menuntut keseimbangan CPU dan GPU. Jangan menilai processor hanya dari jumlah core."},{h:"Perhatikan socket dan platform",p:"Socket menentukan motherboard yang kompatibel. Platform modern juga menentukan dukungan DDR5, jalur PCIe, storage, dan opsi upgrade di masa depan."},{h:"Cache dan gaming workload",p:"Cache besar dapat membantu beberapa game mengurangi akses data ke memory utama. Efeknya berbeda antar game, jadi gunakan benchmark yang relevan dengan resolusi dan GPU target."}],links:[{label:"Shop Processor",href:"/category/processor"},{label:"Open PC Builder",href:"/builder"}]},
 "gpu-1080p-1440p-4k":{title:"GPU untuk 1080p vs 1440p vs 4K",cat:"Graphics Card",intro:"Kelas GPU sebaiknya dipilih dari kombinasi resolusi, refresh rate, preset visual, VRAM, dan target umur pemakaian.",sections:[{h:"1080p: fokus efisiensi",p:"Untuk 1080p high refresh, performa raster yang stabil dan CPU yang cukup cepat sering lebih penting daripada membeli GPU terlalu besar."},{h:"1440p: sweet spot modern gaming",p:"1440p membutuhkan lebih banyak GPU horsepower dan VRAM dibanding 1080p. Monitor 144–180Hz membuat pairing GPU dan CPU semakin penting."},{h:"4K: GPU menjadi pusat anggaran",p:"4K memindahkan bottleneck lebih berat ke GPU. Pastikan PSU, airflow, dan case clearance ikut diperhitungkan."}],links:[{label:"Shop GPU",href:"/category/graphics-card"},{label:"Check Compatibility",href:"/builder"}]},
 "ddr5-32gb-vs-64gb":{title:"DDR5 32GB vs 64GB untuk Gaming dan Creator",cat:"Memory",intro:"32GB adalah titik nyaman untuk banyak gaming PC modern, sementara 64GB mulai relevan untuk creator, heavy multitasking, simulation, dan workload besar.",sections:[{h:"Untuk gaming murni",p:"32GB dual-channel umumnya memberi ruang yang sehat untuk game modern, voice chat, browser, dan background tools."},{h:"Kapan 64GB layak",p:"64GB berguna untuk editing besar, virtual machine, 3D, local AI workload, atau multitasking berat sambil gaming dan streaming."},{h:"Speed dan stability",p:"Jangan hanya mengejar angka MT/s. Stabilitas profile memory, memory controller CPU, dan BIOS motherboard sama pentingnya."}],links:[{label:"Shop DDR5",href:"/category/memory"}]},
 "berapa-watt-psu-gaming":{title:"Berapa Watt PSU yang Dibutuhkan Gaming PC?",cat:"Power Supply",intro:"PSU harus dipilih dari total konsumsi, transient spike, efisiensi, konektor GPU, dan ruang upgrade, bukan sekadar angka watt minimum.",sections:[{h:"Hitung beban utama",p:"GPU dan CPU adalah konsumen daya terbesar. Tambahkan margin untuk fan, storage, USB devices, pump, dan upgrade."},{h:"Sisakan headroom",p:"PSU yang bekerja terus-menerus di batas maksimum tidak ideal. Headroom membantu efisiensi, noise, dan stability saat spike."},{h:"Perhatikan standar modern",p:"ATX 3.x dan konektor GPU modern penting untuk sistem high-end. Kualitas platform PSU lebih penting daripada watt besar tanpa reputasi jelas."}],links:[{label:"Shop PSU",href:"/category/power-supply"},{label:"Use PC Builder",href:"/builder"}]},
 "nvme-gen4-vs-gen5":{title:"NVMe Gen4 vs Gen5: Mana yang Lebih Masuk Akal?",cat:"Storage",intro:"Angka sequential speed tinggi tidak selalu sebanding dengan perbedaan terasa saat gaming. Kapasitas, thermal, harga, dan workload harus ikut dihitung.",sections:[{h:"Gaming load time",p:"Banyak game tidak menggunakan full sequential bandwidth SSD. Gen4 cepat sudah sangat responsif untuk sebagian besar game."},{h:"Creator workload",p:"Transfer file besar, scratch disk, dan workflow media tertentu lebih bisa memanfaatkan storage berkecepatan tinggi."},{h:"Thermal dan motherboard",p:"SSD cepat dapat menghasilkan panas tinggi. Pastikan slot motherboard dan heatsink storage mendukung."}],links:[{label:"Shop NVMe SSD",href:"/category/storage"}]},
 "cara-memilih-gaming-monitor":{title:"Cara Memilih Gaming Monitor: Resolution, Hz, Panel, dan Response Time",cat:"Monitor",intro:"Gaming monitor yang bagus harus cocok dengan kemampuan GPU dan jenis game. Resolusi tinggi tanpa FPS cukup hanya memindahkan bottleneck.",sections:[{h:"Resolution vs refresh rate",p:"1080p cocok untuk competitive FPS tinggi, 1440p memberi detail dan performance balance, sedangkan 4K lebih berat ke GPU."},{h:"Panel dan motion",p:"Fast IPS populer karena balance warna, viewing angle, dan response. Evaluasi overshoot dan actual response, bukan hanya angka marketing."},{h:"Adaptive sync",p:"Variable refresh rate membantu frame pacing ketika FPS berubah. Pastikan GPU dan monitor mendukung standar yang sesuai."}],links:[{label:"Shop Gaming Monitor",href:"/category/monitor"}]},
 "pc-gaming-15-juta":{title:"PC Gaming 15 Juta: Prioritas Budget yang Benar",cat:"Build Guide",intro:"Pada budget terbatas, alokasi uang yang benar lebih penting daripada mengejar satu komponen flagship.",sections:[{h:"Prioritaskan GPU sesuai target",p:"Untuk gaming, GPU biasanya mendapat porsi terbesar. Sisakan budget cukup untuk CPU, PSU, storage, dan monitor yang seimbang."},{h:"Jangan potong kualitas PSU",p:"PSU murah dengan kualitas buruk bisa menjadi titik lemah seluruh sistem. Pilih kapasitas dan kualitas sesuai kebutuhan nyata."},{h:"Bangun jalur upgrade",p:"Motherboard, case, dan PSU yang tepat memberi ruang upgrade tanpa mengganti terlalu banyak komponen."}],links:[{label:"Start PC Builder",href:"/builder"}]},
 "pc-gaming-25-juta":{title:"PC Gaming 25 Juta untuk 1440p High Refresh",cat:"Build Guide",intro:"Budget 25 juta membuka ruang untuk 1440p high-refresh yang seimbang jika distribusi komponen tidak terlalu berat ke kosmetik.",sections:[{h:"GPU dan monitor harus satu target",p:"Pilih GPU berdasarkan target FPS di 1440p dan pastikan monitor mampu menampilkan refresh rate yang ingin dicapai."},{h:"CPU jangan jadi bottleneck",p:"Untuk game competitive, CPU tetap penting. Untuk AAA ultra, GPU akan mengambil porsi beban lebih besar."},{h:"Thermal dan airflow",p:"Komponen lebih cepat menghasilkan panas lebih tinggi. Case airflow dan cooling harus masuk budget sejak awal."}],links:[{label:"Build 1440p Rig",href:"/builder"}]},
 "checklist-kompatibilitas-pc":{title:"Checklist Kompatibilitas Sebelum Merakit PC",cat:"PC Builder",intro:"Sebelum checkout, cek enam titik rawan: socket CPU, memory generation, GPU clearance, PSU capacity, CPU cooler support, dan radiator/case clearance.",sections:[{h:"CPU + motherboard + RAM",p:"Socket CPU dan motherboard harus sama. Motherboard juga menentukan memory generation dan kapasitas yang didukung."},{h:"GPU + PSU + case",p:"Pastikan PSU memenuhi kebutuhan daya dan connector, sementara case punya panjang GPU dan slot expansion yang cukup."},{h:"Cooling + airflow",p:"CPU cooler harus mendukung socket dan muat di case. Untuk AIO, cek ukuran radiator dan posisi mounting."}],links:[{label:"Open Compatibility Engine",href:"/builder"},{label:"Shop All Components",href:"/category/all"}]}
};

export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const a=articles[slug];return{title:a?.title||"NEXRIG Guide",description:a?.intro||"NEXRIG gaming PC hardware guide"}}

export default async function Article({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const a=articles[slug]||articles["checklist-kompatibilitas-pc"];return <main><header className="topbar"><Link href="/" className="brand">NEX<span>RIG</span></Link><Link href="/blog">Guides</Link></header><article className="articlePage"><div className="articleBread"><Link href="/">Home</Link><span>›</span><Link href="/blog">Guides</Link><span>›</span><b>{a.cat}</b></div><span className="kicker">{a.cat.toUpperCase()}</span><h1>{a.title}</h1><p className="articleLead">{a.intro}</p><div className="articleMeta">NEXRIG Editorial · Updated 2026 · 6 min read</div><div className="toc"><b>In this guide</b>{a.sections.map((s,i)=><a href={`#s${i}`} key={s.h}>{s.h}</a>)}</div>{a.sections.map((s,i)=><section id={`s${i}`} key={s.h}><h2>{s.h}</h2><p>{s.p}</p></section>)}<div className="articleCta"><h2>Turn the guide into a build</h2><p>Compare parts, verify compatibility, then continue to the relevant NEXRIG category.</p><div>{a.links.map(l=><Link key={l.href} href={l.href}>{l.label}</Link>)}</div></div></article></main>}
